import { useState, useCallback } from 'react';

// ==========================================
// 内置高频词词典 — 覆盖2932个常见词汇
// 所有词条均带词性标注：v.动词 n.名词 adj.形容词 adv.副词 prep.介词 conj.连词 pron.代词 num.数词
// 本地查表 — 零延迟、零网络请求、100%可用
// ==========================================
const DICTIONARY: Record<string, string> = {
  be: 'v.是；存在',   am: 'v.是',   is: 'v.是',
  are: 'v.是',   was: 'v.是（过去式）',   were: 'v.是（过去式）',
  being: 'v.正在',   been: 'v.已经',   have: 'v.有',
  has: 'v.有（三单）',   had: 'v.有（过去式）',   do: 'v.做；助动词',
  does: 'v.做（三单）',   did: 'v.做（过去式）',   doing: 'v.正在做',
  done: 'v.做完',   go: 'vi.去；走',   goes: 'vi.去（三单）',
  went: 'vi.去（过去式）',   going: 'vi.正在去',   gone: 'vi.已去',
  come: 'vi.来',   came: 'vi.来（过去式）',   coming: 'vi.正在来',
  get: 'v.得到',   got: 'v.得到（过去式）',   getting: 'v.正在得到',
  gotten: 'v.已得到',   make: 'v.制作',   made: 'vt.制作（过去式）',
  making: 'vt.正在制作',   take: 'v.拿',   took: 'vt.拿（过去式）',
  taking: 'vt.正在拿',   taken: 'vt.已拿',   see: 'v.看见',
  saw: 'vt.看见（过去式）',   seen: 'vt.已看见',   seeing: 'vt.正在看',
  know: 'v.知道',   knew: 'v.知道（过去式）',   known: 'v.已知',
  knowing: 'v.知道',   think: 'v.思考',   thought: 'n.想法',
  thinking: 'v.正在思考',   say: 'v.说',   said: 'v.说（过去式）',
  saying: 'v.正在说',   tell: 'v.告诉',   told: 'vt.告诉（过去式）',
  telling: 'vt.正在告诉',   ask: 'v.问；请求',   asked: 'v.问（过去式）',
  asking: 'v.正在问',   give: 'vt.给',   gave: 'vt.给（过去式）',
  given: 'vt.已给',   giving: 'vt.正在给',   find: 'vt.找到；发现',
  found: 'v.建立',   finding: 'vt.正在找',   want: 'v.想要',
  wanted: 'vt.想要（过去式）',   wanting: 'vt.想要',   need: 'v.需要',
  needed: 'v.需要（过去式）',   needing: 'v.需要',   use: 'v.使用',
  used: 'adj.习惯的',   using: 'vt.正在使用',   work: 'v.工作',
  worked: 'v.工作（过去式）',   working: 'v.正在工作',   worker: 'n.工人',
  call: 'v.叫；打电话',   called: 'v.叫（过去式）',   calling: 'v.正在叫',
  try: 'v.尝试',   tried: 'v.尝试（过去式）',   trying: 'v.正在尝试',
  feel: 'v.感觉',   felt: 'v.感觉（过去式）',   feeling: 'n.感觉;v.感觉',
  become: 'v.变成',   became: 'v.变成（过去式）',   becoming: 'v.正在变成',
  leave: 'v.离开',   left: 'n.左边;adj.左边的',   leaving: 'v.正在离开',
  put: 'v.放置',   putting: 'vt.正在放置',   mean: 'v.意思是',
  meant: 'vt.意思是（过去式）',   meaning: 'n.意思',   keep: 'v.保持',
  kept: 'v.保持（过去式）',   keeping: 'v.正在保持',   let: 'vt.让',
  letting: 'vt.正在让',   begin: 'v.开始',   began: 'v.开始（过去式）',
  begun: 'v.已开始',   beginning: 'n.开始',   seem: 'v.似乎',
  seemed: 'vi.似乎（过去式）',   seeming: 'vi.似乎',   help: 'v.帮助',
  helped: 'v.帮助（过去式）',   helping: 'v.正在帮助',   helpful: 'adj.有帮助的',
  show: 'v.展示',   showed: 'v.展示（过去式）',   shown: 'v.已展示',
  showing: 'v.正在展示',   hear: 'v.听见',   heard: 'v.听见（过去式）',
  hearing: 'v.正在听',   play: 'v.玩',   played: 'v.玩（过去式）',
  playing: 'v.正在玩',   run: 'v.跑',   ran: 'v.跑（过去式）',
  running: 'v.正在跑',   move: 'v.移动',   moved: 'v.移动（过去式）',
  moving: 'v.正在移动',   movement: 'n.运动',   live: 'v.生活',
  lived: 'v.生活（过去式）',   living: 'n.生活',   life: 'n.生命；生活',
  believe: 'v.相信',   believed: 'v.相信（过去式）',   believing: 'v.正在相信',
  bring: 'vt.带来',   brought: 'vt.带来（过去式）',   bringing: 'vt.正在带来',
  happen: 'v.发生',   happened: 'vi.发生（过去式）',   happening: 'vi.正在发生',
  stand: 'v.站立',   stood: 'v.站立（过去式）',   standing: 'n.地位;v.站立',
  lose: 'v.失去',   lost: 'v.失去（过去式）;adj.迷路的',   losing: 'v.正在失去',
  loss: 'n.损失',   pay: 'v.支付',   paid: 'v.支付（过去式）',
  paying: 'v.正在支付',   payment: 'n.付款',   meet: 'v.遇见',
  met: 'v.遇见（过去式）',   meeting: 'n.会议;v.正在遇见',   include: 'v.包含',
  included: 'vt.包含（过去式）',   including: 'prep.包括',   continue: 'v.继续',
  continued: 'v.继续（过去式）',   continuing: 'v.正在继续',   set: 'v.设置',
  setting: 'n.环境;v.正在设置',   learn: 'v.学习',   learned: 'v.学习（过去式）',
  learning: 'n.学习;v.正在学习',   change: 'v.改变;n.变化',   changed: 'v.改变（过去式）',
  changing: 'v.正在改变',   lead: 'v.领导',   led: 'v.领导（过去式）',
  leading: 'adj.主要的;v.正在领导',   leader: 'n.领导者',   understand: 'v.理解',
  understood: 'v.理解（过去式）',   understanding: 'n.理解',   watch: 'v.观看',
  watched: 'v.观看（过去式）',   watching: 'v.正在观看',   follow: 'v.跟随',
  followed: 'v.跟随（过去式）',   following: 'adj.接下来的',   stop: 'v.停止',
  stopped: 'v.停止（过去式）',   stopping: 'v.正在停止',   create: 'v.创造',
  created: 'v.创造（过去式）',   creating: 'v.正在创造',   creation: 'n.创造',
  speak: 'v.说话',   spoke: 'v.说话（过去式）',   spoken: 'adj.口头的;v.已说',
  speaking: 'n.说话;v.正在说话',   read: 'v.阅读',   reading: 'n.阅读;v.正在阅读',
  allow: 'v.允许',   allowed: 'v.允许（过去式）',   allowing: 'v.正在允许',
  add: 'v.添加',   added: 'v.添加（过去式）',   adding: 'v.正在添加',
  addition: 'n.加法;增加',   spend: 'v.花费',   spent: 'v.花费（过去式）',
  spending: 'n.支出;v.正在花费',   grow: 'v.成长',   grew: 'v.成长（过去式）',
  grown: 'adj.成年的;v.已成长',   growth: 'n.增长',   open: 'v.打开;adj.开放的',
  opened: 'v.打开（过去式）',   opening: 'n.开口;v.正在打开',   close: 'v.关闭;adj.接近的',
  closed: 'adj.关闭的;v.关闭（过去式）',   walk: 'v.走路',   walked: 'v.走路（过去式）',
  walking: 'v.正在走路',   win: 'v.赢',   won: 'v.赢（过去式）',
  winning: 'adj.获胜的;v.正在赢',   winner: 'n.赢家',   offer: 'v.提供',
  offered: 'v.提供（过去式）',   offering: 'n.提供;v.正在提供',   remember: 'v.记得',
  remembered: 'v.记得（过去式）',   remembering: 'v.正在记得',   memory: 'n.记忆',
  love: 'n.爱;v.爱',   loved: 'v.爱（过去式）',   loving: 'adj.充满爱的',
  lovely: 'adj.可爱的',   consider: 'v.考虑',   considered: 'v.考虑（过去式）',
  considering: 'prep.考虑到;v.正在考虑',   appear: 'vi.出现',   appeared: 'vi.出现（过去式）',
  appearing: 'vi.正在出现',   appearance: 'n.外貌;出现',   buy: 'v.买',
  bought: 'v.买（过去式）',   buying: 'v.正在买',   wait: 'v.等待',
  waited: 'v.等待（过去式）',   waiting: 'v.正在等待',   serve: 'v.服务',
  served: 'v.服务（过去式）',   serving: 'n.一份食物;v.正在服务',   service: 'n.服务',
  die: 'v.死亡',   died: 'v.死亡（过去式）',   dying: 'adj.垂死的',
  dead: 'adj.死亡的',   death: 'n.死亡',   send: 'v.发送',
  sent: 'v.发送（过去式）',   sending: 'v.正在发送',   expect: 'v.期待',
  expected: 'v.期待（过去式）',   expecting: 'v.正在期待',   expectation: 'n.期望',
  build: 'v.建造',   built: 'v.建造（过去式）',   building: 'n.建筑物;v.正在建造',
  stay: 'v.停留',   stayed: 'v.停留（过去式）',   staying: 'v.正在停留',
  fall: 'v.落下',   fell: 'v.落下（过去式）',   fallen: 'adj.倒下的;v.已落下',
  falling: 'v.正在落下',   cut: 'v.切割',   cutting: 'n.剪辑;v.正在切割',
  reach: 'v.到达',   reached: 'v.到达（过去式）',   reaching: 'v.正在到达',
  suggest: 'v.建议',   suggested: 'v.建议（过去式）',   suggestion: 'n.建议',
  raise: 'v.提高',   raised: 'v.提高（过去式）',   raising: 'v.正在提高',
  pass: 'v.通过',   passed: 'v.通过（过去式）',   passing: 'adj.短暂的;v.正在通过',
  sell: 'v.卖',   sold: 'v.卖（过去式）',   selling: 'v.正在卖',
  require: 'v.需要',   required: 'adj.必需的;v.需要（过去式）',   requirement: 'n.要求',
  decide: 'v.决定',   decided: 'v.决定（过去式）',   decision: 'n.决定',
  pull: 'v.拉',   pulled: 'v.拉（过去式）',   pulling: 'v.正在拉',
  start: 'v.开始',   started: 'v.开始（过去式）',   starting: 'v.正在开始',
  develop: 'v.发展',   developed: 'adj.发达的;v.发展（过去式）',   development: 'n.发展',
  turn: 'v.转动',   turned: 'v.转动（过去式）',   turning: 'n.转弯处;v.正在转动',
  return: 'v.返回',   returned: 'v.返回（过去式）',   returning: 'v.正在返回',
  increase: 'v.增加',   increased: 'v.增加（过去式）;adj.增加的',   write: 'v.写',
  wrote: 'v.写（过去式）',   written: 'adj.书面的;v.已写',   writer: 'n.作家',
  provide: 'v.提供',   provided: 'conj.假如;v.提供（过去式）',   providing: 'v.正在提供',
  sit: 'v.坐',   sat: 'v.坐（过去式）',   sitting: 'v.正在坐',
  lie: 'v.躺；说谎',   lay: 'v.放置',   lain: 'v.已躺',
  lying: 'v.正在躺;adj.躺着的',   eat: 'v.吃',   ate: 'v.吃（过去式）',
  eaten: 'v.已吃',   eating: 'v.正在吃',   drink: 'v.喝',
  drank: 'v.喝（过去式）',   drunk: 'adj.喝醉的;v.已喝',   drinking: 'n.饮酒;v.正在喝',
  sleep: 'v.睡觉',   slept: 'v.睡觉（过去式）',   sleeping: 'adj.睡着的;v.正在睡觉',
  drive: 'v.驾驶',   drove: 'v.驾驶（过去式）',   driven: 'adj.有动力的;v.已驾驶',
  driving: 'n.驾驶;v.正在驾驶',   accept: 'v.接受',   achieve: 'v.达到',
  act: 'v.行动',   adapt: 'v.适应',   address: 'v.解决;n.地址',
  admire: 'v.钦佩',   admit: 'v.承认',   adopt: 'v.采用',
  advance: 'v.前进',   advertise: 'v.做广告',   advise: 'v.建议',
  affect: 'v.影响',   afford: 'v.负担得起',   agree: 'v.同意',
  aim: 'v.瞄准;n.目标',   alarm: 'v.警告;n.警报',   announce: 'v.宣布',
  annoy: 'v.惹恼',   apologize: 'v.道歉',   appeal: 'v.呼吁',
  apply: 'v.申请',   appoint: 'v.任命',   appreciate: 'v.欣赏',
  approach: 'v.接近;n.方法',   approve: 'v.批准',   argue: 'v.争论',
  arise: 'v.出现',   arrange: 'v.安排',   arrest: 'v.逮捕',
  arrive: 'v.到达',   assign: 'v.分配',   assist: 'v.协助',
  assume: 'v.假设',   attach: 'v.附加',   attack: 'v.攻击',
  attend: 'v.参加',   attract: 'v.吸引',   avoid: 'v.避免',
  awake: 'v.醒来',   back: 'v.支持;n.背部',   bake: 'v.烘焙',
  ban: 'v.禁止',   beat: 'v.打败',   behave: 'v.表现',
  belong: 'v.属于',   benefit: 'v.受益;n.利益',   bet: 'v.打赌',
  bind: 'v.捆绑',   bite: 'v.咬',   blame: 'v.责备',
  bleed: 'v.流血',   bless: 'v.祝福',   blow: 'v.吹',
  boil: 'v.煮沸',   bomb: 'v.轰炸',   book: 'v.预订;n.书',
  borrow: 'v.借',   bother: 'v.打扰',   bounce: 'v.弹跳',
  bow: 'v.鞠躬',   brake: 'v.刹车',   branch: 'v.分支;n.分支',
  brand: 'n.品牌',   breast: 'n.乳房',   breath: 'n.呼吸',
  breathe: 'v.呼吸',   breed: 'v.繁殖',   broadcast: 'v.广播',
  brush: 'v.刷',   burn: 'v.燃烧',   bury: 'v.埋葬',
  bush: 'n.灌木',   butter: 'n.黄油',   button: 'n.按钮',
  cake: 'n.蛋糕',   calculate: 'v.计算',   calm: 'v.使平静;adj.平静的',
  camp: 'v.露营;n.营地',   cancel: 'v.取消',   capture: 'v.捕获',
  care: 'v.关心;n.照顾',   carry: 'v.携带',   cart: 'n.手推车',
  carve: 'v.雕刻',   cash: 'n.现金',   cast: 'v.投',
  catch: 'v.抓住',   cause: 'v.导致;n.原因',   cease: 'v.停止',
  celebrate: 'v.庆祝',   chain: 'n.链条',   challenge: 'v.挑战;n.挑战',
  champion: 'n.冠军',   channel: 'n.频道',   chapter: 'n.章节',
  charge: 'v.收费;n.费用',   charm: 'n.魅力',   chase: 'v.追逐',
  chat: 'v.聊天',   cheat: 'v.欺骗',   cheer: 'v.欢呼',
  cheese: 'n.奶酪',   chest: 'n.胸部',   chicken: 'n.鸡;鸡肉',
  chief: 'n.首领;adj.主要的',   chocolate: 'n.巧克力',   choice: 'n.选择',
  choose: 'v.选择',   church: 'n.教堂',   cigarette: 'n.香烟',
  circle: 'n.圆圈',   citizen: 'n.公民',   claim: 'v.声称;n.索赔',
  clap: 'v.鼓掌',   clarify: 'v.澄清',   clash: 'v.冲突',
  classify: 'v.分类',   claw: 'n.爪子',   clay: 'n.粘土',
  clean: 'v.清洁;adj.干净的',   clerk: 'n.职员',   click: 'v.点击',
  cliff: 'n.悬崖',   climb: 'v.爬',   cling: 'v. cling',
  clinic: 'n.诊所',   clip: 'v.剪辑;n.夹子',   clock: 'n.时钟',
  clone: 'v.克隆',   cloth: 'n.布',   clothe: 'v.给...穿衣',
  cloud: 'n.云',   club: 'n.俱乐部',   clue: 'n.线索',
  clumsy: 'adj.笨拙的',   coach: 'n.教练',   coal: 'n.煤',
  coast: 'n.海岸',   coat: 'n.外套',   code: 'n.代码',
  coffee: 'n.咖啡',   coin: 'n.硬币',   collapse: 'v.倒塌',
  collar: 'n.衣领',   collect: 'v.收集',   college: 'n.大学',
  combine: 'v.结合',   comfort: 'n.安慰',   command: 'v.命令;n.命令',
  comment: 'n.评论',   commit: 'v.承诺',   communicate: 'v.交流',
  compare: 'v.比较',   compete: 'v.竞争',   complain: 'v.抱怨',
  complete: 'v.完成;adj.完整的',   complex: 'adj.复杂的',   compose: 'v.作曲',
  concentrate: 'v.集中',   concern: 'v.涉及;n.担忧',   conclude: 'v.结论',
  concrete: 'n.混凝土;adj.具体的',   condition: 'n.条件',   conduct: 'v.进行;n.行为',
  confess: 'v.坦白',   confidence: 'n.信心',   confirm: 'v.确认',
  conflict: 'n.冲突',   confuse: 'v.使困惑',   congratulate: 'v.祝贺',
  connect: 'v.连接',   conscience: 'n.良心',   conscious: 'adj.有意识的',
  consent: 'n.同意',   conserve: 'v.保存',   consist: 'v.由...组成',
  constant: 'adj.不断的',   construct: 'v.建造',   consult: 'v.咨询',
  consume: 'v.消费',   contact: 'n.联系;v.联系',   contain: 'v.包含',
  contemporary: 'adj.当代的',   content: 'n.内容;adj.满足的',   contest: 'n.比赛',
  context: 'n.上下文',   contract: 'n.合同',   contrary: 'adj.相反的',
  contrast: 'n.对比',   contribute: 'v.贡献',   control: 'v.控制;n.控制',
  controversy: 'n.争议',   convenient: 'adj.方便的',   conversation: 'n.对话',
  convert: 'v.转换',   convey: 'v.传达',   convince: 'v.说服',
  cook: 'v.烹饪',   cool: 'v.冷却;adj.凉爽的',   cooperate: 'v.合作',
  cope: 'v.应对',   copy: 'v.复制;n.副本',   corn: 'n.玉米',
  correct: 'v.纠正;adj.正确的',   corridor: 'n.走廊',   cost: 'v.花费;n.成本',
  cottage: 'n.小屋',   cotton: 'n.棉花',   cough: 'v.咳嗽',
  could: 'v.能',   council: 'n.委员会',   count: 'v.数',
  counter: 'n.柜台',   countryside: 'n.乡村',   county: 'n.县',
  couple: 'n.一对',   courage: 'n.勇气',   course: 'n.课程',
  court: 'n.法庭',   cousin: 'n.堂/表兄弟姐妹',   cover: 'v.覆盖;n.封面',
  cow: 'n.牛',   crack: 'v.破裂',   craft: 'n.工艺',
  crash: 'v.撞毁',   crawl: 'v.爬行',   crazy: 'adj.疯狂的',
  cream: 'n.奶油',   creature: 'n.生物',   credit: 'n.信用',
  crew: 'n.船员',   crime: 'n.犯罪',   crisis: 'n.危机',
  critic: 'n.评论家',   criticize: 'v.批评',   crop: 'n.庄稼',
  cross: 'v.穿过;n.十字架',   crowd: 'n.人群',   crown: 'n.王冠',
  crucial: 'adj.关键的',   cruel: 'adj.残酷的',   cry: 'v.哭',
  culture: 'n.文化',   cup: 'n.杯子',   cupboard: 'n.橱柜',
  cure: 'v.治愈',   curious: 'adj.好奇的',   curl: 'v.卷曲',
  current: 'adj.当前的;n.水流',   curtain: 'n.窗帘',   curve: 'n.曲线',
  cushion: 'n.垫子',   custom: 'n.习俗',   customer: 'n.顾客',
  cycle: 'n.周期;v.骑自行车',   daily: 'adj.每日的',   damage: 'v.损害;n.损害',
  dance: 'v.跳舞',   dare: 'v.敢',   dark: 'adj.黑暗的',
  data: 'n.数据',   date: 'n.日期;约会',   daughter: 'n.女儿',
  dawn: 'n.黎明',   deal: 'v.处理;n.交易',   debate: 'n.辩论',
  debt: 'n.债务',   decade: 'n.十年',   deck: 'n.甲板',
  declare: 'v.宣布',   decline: 'v.下降',   decorate: 'v.装饰',
  decrease: 'v.减少',   defeat: 'v.击败',   defend: 'v.防御',
  define: 'v.定义',   degree: 'n.度;程度',   delay: 'v.延迟',
  deliberate: 'adj.故意的',   deliver: 'v.递送',   demand: 'v.要求;n.需求',
  demonstrate: 'v.演示',   dentist: 'n.牙医',   deny: 'v.否认',
  depart: 'v.离开',   depend: 'v.依赖',   deposit: 'n.存款',
  depress: 'v.使沮丧',   derive: 'v.得到',   describe: 'v.描述',
  desert: 'n.沙漠;v.抛弃',   deserve: 'v.值得',   design: 'v.设计;n.设计',
  desk: 'n.书桌',   despair: 'n.绝望',   destroy: 'v.摧毁',
  detect: 'v.发现',   determine: 'v.决定',   device: 'n.装置',
  devote: 'v.致力于',   diagram: 'n.图表',   diamond: 'n.钻石',
  diary: 'n.日记',   dictate: 'v.口述',   dictionary: 'n.词典',
  diet: 'n.饮食',   dig: 'v.挖',   digital: 'adj.数字的',
  dignity: 'n.尊严',   dimension: 'n.维度',   dinner: 'n.晚餐',
  dip: 'v.蘸',   diploma: 'n.文凭',   direct: 'adj.直接的;v.指导',
  dirt: 'n.泥土',   disadvantage: 'n.劣势',   disagree: 'v.不同意',
  disappear: 'v.消失',   disappoint: 'v.使失望',   disaster: 'n.灾难',
  discipline: 'n.纪律',   discount: 'n.折扣',   discourage: 'v.使气馁',
  discover: 'v.发现',   discuss: 'v.讨论',   disease: 'n.疾病',
  disgust: 'n.厌恶',   dish: 'n.盘子',   dismiss: 'v.解雇',
  disorder: 'n.混乱',   display: 'v.展示;n.展示',   distance: 'n.距离',
  distant: 'adj.遥远的',   distinct: 'adj.明显的',   distinguish: 'v.区分',
  distribute: 'v.分发',   district: 'n.区域',   disturb: 'v.打扰',
  dive: 'v.潜水',   divide: 'v.分开',   divorce: 'n.离婚',
  doctor: 'n.医生',   document: 'n.文件',   dog: 'n.狗',
  doll: 'n.玩偶',   dollar: 'n.美元',   domestic: 'adj.国内的',
  donate: 'v.捐赠',   door: 'n.门',   dose: 'n.剂量',
  dot: 'n.点',   double: 'adj.双倍的',   doubt: 'n.怀疑;v.怀疑',
  dough: 'n.面团',   dozen: 'n.一打',   draft: 'n.草稿',
  drag: 'v.拖',   drain: 'v.排水',   drama: 'n.戏剧',
  draw: 'v.画',   drawer: 'n.抽屉',   dream: 'n.梦;v.做梦',
  dress: 'n.连衣裙;v.穿衣',   drill: 'n.钻',   driver: 'n.司机',
  drop: 'v.掉落;n.滴',   drug: 'n.药物',   drum: 'n.鼓',
  dry: 'v.擦干;adj.干的',   duck: 'n.鸭子',   dull: 'adj.无聊的',
  dumb: 'adj.哑的',   dump: 'v.倾倒',   duration: 'n.持续时间',
  during: 'prep.在...期间',   dust: 'n.灰尘',   duty: 'n.职责',
  dwell: 'v.居住',   eager: 'adj.渴望的',   eagle: 'n.鹰',
  ear: 'n.耳朵',   earn: 'v.赚取',   earnest: 'adj.认真的',
  earthquake: 'n.地震',   ease: 'n.容易',   east: 'n.东',
  echo: 'n.回声',   economy: 'n.经济',   edge: 'n.边缘',
  edit: 'v.编辑',   educate: 'v.教育',   effect: 'n.效果',
  efficient: 'adj.高效的',   effort: 'n.努力',   egg: 'n.蛋',
  elbow: 'n.肘',   elder: 'adj.年长的',   elect: 'v.选举',
  electric: 'adj.电的',   elegant: 'adj.优雅的',   element: 'n.元素',
  elephant: 'n.大象',   eliminate: 'v.消除',   elite: 'n.精英',
  else: 'adv.其他',   embarrass: 'v.使尴尬',   emerge: 'v.出现',
  emotion: 'n.情感',   emperor: 'n.皇帝',   emphasis: 'n.强调',
  empire: 'n.帝国',   employ: 'v.雇佣',   empty: 'adj.空的;v.清空',
  enable: 'v.使能够',   encounter: 'v.遇到',   encourage: 'v.鼓励',
  end: 'n.结束;v.结束',   enemy: 'n.敌人',   energy: 'n.能量',
  engage: 'v.从事',   engine: 'n.引擎',   enjoy: 'v.享受',
  enormous: 'adj.巨大的',   ensure: 'v.确保',   enter: 'v.进入',
  entertain: 'v.娱乐',   enthusiasm: 'n.热情',   entire: 'adj.整个的',
  entrance: 'n.入口',   entry: 'n.进入',   envelope: 'n.信封',
  environment: 'n.环境',   envy: 'v.嫉妒',   episode: 'n.集',
  equal: 'adj.相等的',   equip: 'v.装备',   era: 'n.时代',
  escape: 'v.逃跑',   especially: 'adv.尤其',   essay: 'n.文章',
  essence: 'n.本质',   establish: 'v.建立',   estate: 'n.房地产',
  estimate: 'v.估计',   eternal: 'adj.永恒的',   ethics: 'n.伦理',
  evacuate: 'v.撤离',   evaluate: 'v.评估',   even: 'adv.甚至;adj.平坦的',
  event: 'n.事件',   eventually: 'adv.最终',   ever: 'adv.曾经',
  everyday: 'adj.每天的',   evidence: 'n.证据',   evil: 'adj.邪恶的',
  evolve: 'v.进化',   exact: 'adj.精确的',   exaggerate: 'v.夸大',
  exam: 'n.考试',   examine: 'v.检查',   example: 'n.例子',
  exceed: 'v.超过',   excellent: 'adj.优秀的',   except: 'prep.除了',
  exchange: 'v.交换',   excite: 'v.使兴奋',   exclaim: 'v.呼喊',
  exclude: 'v.排除',   excuse: 'n.借口;v.原谅',   execute: 'v.执行',
  exercise: 'n.练习;v.锻炼',   exhaust: 'v.耗尽',   exhibit: 'v.展示',
  exist: 'v.存在',   exit: 'n.出口',   expand: 'v.扩展',
  expense: 'n.费用',   expensive: 'adj.昂贵的',   experiment: 'n.实验',
  expert: 'n.专家',   explain: 'v.解释',   explode: 'v.爆炸',
  explore: 'v.探索',   export: 'v.出口',   expose: 'v.暴露',
  express: 'v.表达',   extend: 'v.延伸',   extent: 'n.程度',
  extreme: 'adj.极端的',   eye: 'n.眼睛',   fabric: 'n.织物',
  face: 'n.脸;v.面对',   facility: 'n.设施',   fact: 'n.事实',
  factor: 'n.因素',   factory: 'n.工厂',   fade: 'v.褪色',
  fail: 'v.失败',   faint: 'adj.微弱的',   fair: 'adj.公平的;n.集市',
  faith: 'n.信仰',   fake: 'adj.假的',   false: 'adj.错误的',
  fame: 'n.名声',   familiar: 'adj.熟悉的',   fan: 'n.粉丝;风扇',
  fancy: 'adj.精致的',   fantastic: 'adj.极好的',   far: 'adj.远的',
  farm: 'n.农场',   fascinate: 'v.迷住',   fashion: 'n.时尚',
  fasten: 'v.系紧',   fat: 'adj.胖的',   fatal: 'adj.致命的',
  fate: 'n.命运',   fault: 'n.过错',   favor: 'n.帮助',
  favorite: 'adj.最喜欢的',   fear: 'n.恐惧;v.害怕',   feather: 'n.羽毛',
  feature: 'n.特征',   federal: 'adj.联邦的',   fee: 'n.费用',
  feed: 'v.喂养',   female: 'adj.女性的',   fence: 'n.栅栏',
  festival: 'n.节日',   fetch: 'v.取',   fever: 'n.发烧',
  few: 'adj.很少的',   fiction: 'n.小说',   field: 'n.领域;田野',
  fierce: 'adj.凶猛的',   fight: 'v.战斗',   figure: 'n.数字;人物',
  file: 'n.文件',   fill: 'v.填满',   film: 'n.电影',
  filter: 'n.过滤器',   final: 'adj.最终的',   finance: 'n.金融',
  finger: 'n.手指',   finish: 'v.完成',   fire: 'n.火;v.解雇',
  firm: 'adj.坚固的;n.公司',   fish: 'n.鱼;v.钓鱼',   fist: 'n.拳头',
  fit: 'v.适合;adj.健康的',   fix: 'v.修理',   flag: 'n.旗帜',
  flame: 'n.火焰',   flash: 'n.闪光',   flat: 'adj.平坦的;n.公寓',
  flavor: 'n.味道',   flee: 'v.逃跑',   fleet: 'n.舰队',
  flesh: 'n.肉',   flight: 'n.飞行',   float: 'v.漂浮',
  flock: 'n.群',   flood: 'n.洪水',   floor: 'n.地板',
  flour: 'n.面粉',   flourish: 'v.繁荣',   flow: 'v.流动',
  flower: 'n.花',   flu: 'n.流感',   fluent: 'adj.流利的',
  fly: 'v.飞',   foam: 'n.泡沫',   focus: 'v.集中;n.焦点',
  fog: 'n.雾',   fold: 'v.折叠',   folk: 'n.人们',
  fool: 'n.傻瓜',   foolish: 'adj.愚蠢的',   foot: 'n.脚',
  football: 'n.足球',   force: 'n.力量;v.强迫',   forecast: 'n.预报',
  forehead: 'n.前额',   foreign: 'adj.外国的',   forest: 'n.森林',
  forever: 'adv.永远',   forget: 'v.忘记',   forgive: 'v.原谅',
  fork: 'n.叉子',   form: 'n.形式;v.形成',   formal: 'adj.正式的',
  format: 'n.格式',   former: 'adj.以前的',   formula: 'n.公式',
  fortune: 'n.财富',   forum: 'n.论坛',   forward: 'adv.向前',
  foster: 'v.培养',   foundation: 'n.基础',   fountain: 'n.喷泉',
  fox: 'n.狐狸',   frame: 'n.框架',   framework: 'n.框架',
  frank: 'adj.坦率的',   free: 'adj.自由的',   freedom: 'n.自由',
  freeze: 'v.冻结',   frequent: 'adj.频繁的',   fresh: 'adj.新鲜的',
  friction: 'n.摩擦',   friend: 'n.朋友',   frighten: 'v.使害怕',
  frog: 'n.青蛙',   from: 'prep.从',   front: 'n.前面',
  frost: 'n.霜',   frown: 'v.皱眉',   fruit: 'n.水果',
  frustrate: 'v.使沮丧',   fry: 'v.油炸',   fuel: 'n.燃料',
  fulfill: 'v.履行',   full: 'adj.满的',   fun: 'n.乐趣',
  function: 'n.功能',   fund: 'n.资金',   fundamental: 'adj.基本的',
  funeral: 'n.葬礼',   funny: 'adj.有趣的',   fur: 'n.毛皮',
  furious: 'adj.狂怒的',   furnace: 'n.炉子',   furnish: 'v.布置',
  furniture: 'n.家具',   further: 'adv.更远',   fuss: 'n.大惊小怪',
  future: 'n.未来',   gain: 'v.获得',   gallery: 'n.画廊',
  gallon: 'n.加仑',   gamble: 'v.赌博',   gap: 'n.缺口',
  garage: 'n.车库',   garbage: 'n.垃圾',   garden: 'n.花园',
  garlic: 'n.大蒜',   gas: 'n.气体;汽油',   gate: 'n.大门',
  gather: 'v.收集',   gauge: 'n.测量仪',   gaze: 'v.凝视',
  gear: 'n.齿轮',   gender: 'n.性别',   gene: 'n.基因',
  generation: 'n.一代人',   generous: 'adj.慷慨的',   genius: 'n.天才',
  gentle: 'adj.温柔的',   gentleman: 'n.绅士',   genuine: 'adj.真正的',
  gesture: 'n.手势',   ghost: 'n.鬼',   giant: 'n.巨人;adj.巨大的',
  gift: 'n.礼物',   giraffe: 'n.长颈鹿',   glad: 'adj.高兴的',
  glance: 'v.瞥一眼',   glare: 'v.怒视',   glass: 'n.玻璃;眼镜',
  glide: 'v.滑行',   glimpse: 'n.一瞥',   global: 'adj.全球的',
  glory: 'n.荣耀',   glove: 'n.手套',   glow: 'v.发光',
  glue: 'n.胶水',   goal: 'n.目标',   goat: 'n.山羊',
  god: 'n.上帝',   gold: 'n.金色',   golf: 'n.高尔夫',
  goodbye: 'int.再见',   goods: 'n.货物',   govern: 'v.统治',
  grab: 'v.抓住',   grace: 'n.优雅',   grade: 'n.等级',
  gradual: 'adj.逐渐的',   graduate: 'v.毕业',   grain: 'n.谷物',
  grand: 'adj.宏伟的',   grant: 'v.授予',   grape: 'n.葡萄',
  graph: 'n.图表',   grasp: 'v.抓住',   grass: 'n.草',
  grateful: 'adj.感激的',   grave: 'n.坟墓;adj.严重的',   gravity: 'n.重力',
  gray: 'n.灰色',   grease: 'n.油脂',   great: 'adj.伟大的',
  greedy: 'adj.贪婪的',   greenhouse: 'n.温室',   greet: 'v.问候',
  grid: 'n.网格',   grief: 'n.悲伤',   grill: 'n.烤架',
  grim: 'adj.严峻的',   grin: 'v.咧嘴笑',   grind: 'v.研磨',
  grip: 'v.紧握',   grocer: 'n.杂货商',   grocery: 'n.杂货',
  ground: 'n.地面',   group: 'n.组',   guarantee: 'v.保证',
  guard: 'n.卫兵;v.保卫',   guess: 'v.猜',   guest: 'n.客人',
  guide: 'n.向导;v.引导',   guideline: 'n.指导方针',   guilt: 'n.内疚',
  guilty: 'adj.内疚的',   guitar: 'n.吉他',   gulf: 'n.海湾',
  gun: 'n.枪',   guy: 'n.家伙',   gym: 'n.健身房',
  habit: 'n.习惯',   habitat: 'n.栖息地',   hail: 'n.冰雹',
  hair: 'n.头发',   half: 'n.一半',   hall: 'n.大厅',
  halt: 'v.停止',   ham: 'n.火腿',   hamburger: 'n.汉堡',
  hammer: 'n.锤子',   hand: 'n.手',   handful: 'n.一把',
  handle: 'v.处理;n.把手',   handy: 'adj.方便的',   hang: 'v.悬挂',
  harbor: 'n.港口',   hardly: 'adv.几乎不',   hardship: 'n.困难',
  hardware: 'n.硬件',   harm: 'n.伤害;v.伤害',   harmony: 'n.和谐',
  harness: 'v.利用',   harvest: 'n.收获',   haste: 'n.匆忙',
  hat: 'n.帽子',   hatch: 'v.孵化',   hate: 'v.恨',
  haunt: 'v.萦绕',   hawk: 'n.鹰',   hay: 'n.干草',
  hazard: 'n.危险',   headache: 'n.头痛',   headline: 'n.头条',
  headquarters: 'n.总部',   heal: 'v.治愈',   heap: 'n.堆',
  heat: 'n.热;v.加热',   heaven: 'n.天堂',   hedge: 'n.树篱',
  heel: 'n.脚后跟',   height: 'n.高度',   heir: 'n.继承人',
  helicopter: 'n.直升机',   hell: 'n.地狱',   helmet: 'n.头盔',
  hen: 'n.母鸡',   hence: 'adv.因此',   herb: 'n.草药',
  herd: 'n.兽群',   here: 'adv.这里',   hero: 'n.英雄',
  heroine: 'n.女英雄',   hesitate: 'v.犹豫',   hide: 'v.隐藏',
  highway: 'n.公路',   hike: 'v.远足',   hill: 'n.小山',
  hinder: 'v.阻碍',   hint: 'n.暗示',   hip: 'n.臀部',
  hire: 'v.雇佣',   hit: 'v.击打',   hobby: 'n.爱好',
  hold: 'v.握住',   hole: 'n.洞',   holiday: 'n.假期',
  hollow: 'adj.空心的',   holy: 'adj.神圣的',   honor: 'n.荣誉',
  hook: 'n.钩子',   hope: 'n.希望;v.希望',   horizon: 'n.地平线',
  horn: 'n.角',   horror: 'n.恐惧',   horse: 'n.马',
  hospital: 'n.医院',   host: 'n.主人',   hostile: 'adj.敌对的',
  hotel: 'n.酒店',   hour: 'n.小时',   household: 'n.家庭',
  housewife: 'n.家庭主妇',   hover: 'v.盘旋',   howl: 'v.嚎叫',
  hug: 'v.拥抱',   huge: 'adj.巨大的',   hum: 'v.哼唱',
  human: 'n.人类;adj.人类的',   humble: 'adj.谦逊的',   humid: 'adj.潮湿的',
  humor: 'n.幽默',   hunger: 'n.饥饿',   hunt: 'v.打猎',
  hurry: 'v.匆忙',   hurt: 'v.伤害',   husband: 'n.丈夫',
  hut: 'n.小屋',   hydrogen: 'n.氢',   hypothesis: 'n.假设',
  ice: 'n.冰',   idea: 'n.想法',   ideal: 'adj.理想的',
  identical: 'adj.相同的',   identify: 'v.识别',   idiom: 'n.习语',
  idle: 'adj.空闲的',   if: 'conj.如果',   ignore: 'v.忽视',
  illustrate: 'v.说明',   image: 'n.图像',   imagine: 'v.想象',
  imitate: 'v.模仿',   immediate: 'adj.立即的',   immense: 'adj.巨大的',
  immigrant: 'n.移民',   immune: 'adj.免疫的',   impact: 'n.影响',
  imperial: 'adj.帝国的',   implement: 'v.实施',   imply: 'v.暗示',
  import: 'v.进口',   impress: 'v.使印象深刻',   improve: 'v.改善',
  inch: 'n.英寸',   incident: 'n.事件',   incline: 'v.倾斜',
  income: 'n.收入',   incorporate: 'v.合并',   indeed: 'adv.确实',
  independence: 'n.独立',   index: 'n.索引',   indicate: 'v.表明',
  individual: 'adj.个人的',   indoor: 'adj.室内的',   induce: 'v.诱导',
  industry: 'n.工业',   inevitable: 'adj.不可避免的',   infant: 'n.婴儿',
  infect: 'v.感染',   infer: 'v.推断',   infinite: 'adj.无限的',
  influence: 'n.影响;v.影响',   inform: 'v.通知',   informal: 'adj.非正式的',
  ingredient: 'n.成分',   inhabit: 'v.居住',   inherit: 'v.继承',
  initial: 'adj.最初的',   initiate: 'v.发起',   inject: 'v.注射',
  injure: 'v.伤害',   ink: 'n.墨水',   inn: 'n.客栈',
  innocent: 'adj.无辜的',   innovate: 'v.创新',   input: 'n.输入',
  inquire: 'v.询问',   insect: 'n.昆虫',   insert: 'v.插入',
  inside: 'prep.在...里面',   insight: 'n.洞察力',   insist: 'v.坚持',
  inspect: 'v.检查',   inspire: 'v.激励',   install: 'v.安装',
  instance: 'n.例子',   instant: 'adj.立即的',   instead: 'adv.代替',
  instinct: 'n.本能',   institute: 'n.学院',   instruct: 'v.指导',
  instrument: 'n.乐器;仪器',   insult: 'v.侮辱',   insurance: 'n.保险',
  integrate: 'v.整合',   integrity: 'n.正直',   intellectual: 'adj.智力的',
  intelligent: 'adj.聪明的',   intend: 'v.打算',   intense: 'adj.强烈的',
  intent: 'n.意图',   interact: 'v.互动',   interest: 'n.兴趣',
  interfere: 'v.干涉',   interior: 'n.内部',   intermediate: 'adj.中间的',
  internal: 'adj.内部的',   international: 'adj.国际的',   interpret: 'v.解释',
  interrupt: 'v.打断',   interval: 'n.间隔',   interview: 'n.面试',
  intimate: 'adj.亲密的',   into: 'prep.进入',   introduce: 'v.介绍',
  invade: 'v.入侵',   invent: 'v.发明',   invest: 'v.投资',
  investigate: 'v.调查',   invisible: 'adj.看不见的',   invite: 'v.邀请',
  involve: 'v.涉及',   iron: 'n.铁;熨斗',   irrigate: 'v.灌溉',
  irritate: 'v.激怒',   island: 'n.岛',   isolate: 'v.隔离',
  issue: 'n.问题',   item: 'n.项目',   jacket: 'n.夹克',
  jail: 'n.监狱',   jam: 'n.果酱;堵塞',   jar: 'n.罐子',
  jaw: 'n.下巴',   jazz: 'n.爵士乐',   jealous: 'adj.嫉妒的',
  jeans: 'n.牛仔裤',   jet: 'n.喷气',   jewel: 'n.珠宝',
  job: 'n.工作',   jog: 'v.慢跑',   join: 'v.加入',
  joint: 'n.关节;adj.联合的',   joke: 'n.笑话',   journal: 'n.期刊',
  journey: 'n.旅程',   joy: 'n.喜悦',   judge: 'n.法官;v.判断',
  juice: 'n.果汁',   jump: 'v.跳',   jungle: 'n.丛林',
  junior: 'adj.初级的',   jury: 'n.陪审团',   justice: 'n.正义',
  justify: 'v.证明...正当',   keen: 'adj.敏锐的',   kettle: 'n.水壶',
  keyboard: 'n.键盘',   kick: 'v.踢',   kid: 'n.小孩',
  kill: 'v.杀死',   kilo: 'n.千克',   kindergarten: 'n.幼儿园',
  king: 'n.国王',   kingdom: 'n.王国',   kiss: 'v.亲吻',
  kit: 'n.工具包',   kitchen: 'n.厨房',   kite: 'n.风筝',
  knee: 'n.膝盖',   kneel: 'v.跪下',   knife: 'n.刀',
  knit: 'v.编织',   knock: 'v.敲',   knot: 'n.结',
  label: 'n.标签',   labor: 'n.劳动',   laboratory: 'n.实验室',
  lack: 'n.缺乏;v.缺乏',   ladder: 'n.梯子',   lady: 'n.女士',
  lag: 'v.落后',   lake: 'n.湖',   lamb: 'n.小羊',
  lamp: 'n.灯',   land: 'n.陆地;v.着陆',   landlord: 'n.房东',
  lane: 'n.小巷',   language: 'n.语言',   lap: 'n.大腿',
  large: 'adj.大的',   laser: 'n.激光',   last: 'adj.最后的',
  late: 'adj.晚的',   lately: 'adv.最近',   latest: 'adj.最新的',
  latter: 'adj.后者的',   laugh: 'v.笑',   launch: 'v.发射',
  laundry: 'n.洗衣店',   law: 'n.法律',   lawn: 'n.草坪',
  lawyer: 'n.律师',   layer: 'n.层',   lazy: 'adj.懒惰的',
  leaf: 'n.叶子',   league: 'n.联盟',   leak: 'v.泄漏',
  lean: 'v.倾斜',   leap: 'v.跳跃',   lease: 'n.租约',
  leather: 'n.皮革',   lecture: 'n.讲座',   legal: 'adj.合法的',
  legend: 'n.传说',   legislation: 'n.立法',   leisure: 'n.休闲',
  lemon: 'n.柠檬',   lend: 'v.借出',   length: 'n.长度',
  lens: 'n.镜头',   leopard: 'n.豹',   lesson: 'n.课',
  letter: 'n.信;字母',   level: 'n.水平',   liberal: 'adj.自由的',
  liberty: 'n.自由',   library: 'n.图书馆',   license: 'n.许可证',
  lid: 'n.盖子',   lift: 'v.举起;n.电梯',   lightning: 'n.闪电',
  likely: 'adj.可能的',   likewise: 'adv.同样地',   limb: 'n.肢体',
  limit: 'n.限制;v.限制',   line: 'n.线',   link: 'n.链接;v.连接',
  lion: 'n.狮子',   lip: 'n.嘴唇',   liquid: 'n.液体;adj.液体的',
  list: 'n.列表;v.列出',   listen: 'v.听',   liter: 'n.升',
  literary: 'adj.文学的',   literature: 'n.文学',   little: 'adj.小的',
  liver: 'n.肝脏',   load: 'n.负担;v.装载',   loaf: 'n.一条面包',
  loan: 'n.贷款',   lobby: 'n.大厅',   local: 'adj.当地的',
  locate: 'v.位于',   lock: 'n.锁;v.锁',   locomotive: 'n.机车',
  lodge: 'v.暂住',   log: 'n.原木;日志',   logic: 'n.逻辑',
  logo: 'n.标志',   lonely: 'adj.孤独的',   long: 'adj.长的',
  look: 'v.看',   loop: 'n.环',   lord: 'n.领主',
  lorry: 'n.卡车（英）',   lot: 'n.许多',   loud: 'adj.大声的',
  lounge: 'n.休息室',   low: 'adj.低的',   loyal: 'adj.忠诚的',
  luck: 'n.运气',   luggage: 'n.行李',   lump: 'n.块',
  lunch: 'n.午餐',   lung: 'n.肺',   luxury: 'n.奢侈',
  machine: 'n.机器',   mad: 'adj.发疯的',   magazine: 'n.杂志',
  magic: 'n.魔法;adj.神奇的',   magnet: 'n.磁铁',   magnificent: 'adj.壮丽的',
  maid: 'n.女仆',   mailbox: 'n.邮箱',   main: 'adj.主要的',
  maintain: 'v.维持',   major: 'adj.主要的',   majority: 'n.大多数',
  male: 'adj.男性的',   mall: 'n.商场',   mammal: 'n.哺乳动物',
  manner: 'n.方式',   manual: 'adj.手工的;n.手册',   manufacture: 'v.制造',
  many: 'adj.很多',   map: 'n.地图',   marathon: 'n.马拉松',
  marble: 'n.大理石',   march: 'v.行进;n.三月',   margin: 'n.边缘',
  marine: 'adj.海洋的',   mark: 'n.标记;v.标记',   market: 'n.市场',
  marriage: 'n.婚姻',   married: 'adj.已婚的',   marry: 'v.结婚',
  marsh: 'n.沼泽',   master: 'n.主人;v.掌握',   mat: 'n.垫子',
  match: 'n.比赛;v.匹配',   mate: 'n.伙伴',   material: 'n.材料',
  math: 'n.数学',   matter: 'n.事情;v.要紧',   mature: 'adj.成熟的',
  maximum: 'n.最大值',   may: 'v.可能;n.五月',   maybe: 'adv.也许',
  mayor: 'n.市长',   meal: 'n.餐',   means: 'n.方法',
  meantime: 'n.同时',   meanwhile: 'adv.同时',   measure: 'v.测量;n.措施',
  meat: 'n.肉',   mechanic: 'n.技工',   medal: 'n.奖牌',
  medical: 'adj.医学的',   medicine: 'n.医学;药物',   medium: 'n.媒体;adj.中等的',
  melt: 'v.融化',   member: 'n.成员',   memorial: 'n.纪念碑',
  mental: 'adj.精神的',   mention: 'v.提及',   menu: 'n.菜单',
  merchant: 'n.商人',   mercy: 'n.仁慈',   mere: 'adj.仅仅的',
  merit: 'n.优点',   mess: 'n.混乱',   message: 'n.消息',
  metal: 'n.金属',   meter: 'n.米;仪表',   method: 'n.方法',
  microphone: 'n.麦克风',   microscope: 'n.显微镜',   microwave: 'n.微波炉',
  midday: 'n.中午',   middle: 'n.中间',   midnight: 'n.午夜',
  might: 'v.可能;n.力量',   mild: 'adj.温和的',   mile: 'n.英里',
  military: 'adj.军事的',   milk: 'n.牛奶',   mill: 'n.磨坊',
  millimeter: 'n.毫米',   million: 'num.百万',   mind: 'n.思想;v.介意',
  mine: 'pron.我的;n.矿',   mineral: 'n.矿物',   minimum: 'n.最小值',
  minister: 'n.部长',   minor: 'adj.较小的',   minority: 'n.少数',
  minus: 'prep.减去',   miracle: 'n.奇迹',   mirror: 'n.镜子',
  miss: 'v.想念;错过',   missile: 'n.导弹',   missing: 'adj.失踪的',
  mission: 'n.任务',   mist: 'n.薄雾',   mistake: 'n.错误',
  mix: 'v.混合',   mixture: 'n.混合物',   moan: 'v.呻吟',
  mobile: 'adj.移动的',   mock: 'v.嘲笑',   mode: 'n.模式',
  model: 'n.模型',   moderate: 'adj.适度的',   modern: 'adj.现代的',
  modest: 'adj.谦虚的',   modify: 'v.修改',   moist: 'adj.潮湿的',
  molecule: 'n.分子',   moment: 'n.时刻',   money: 'n.钱',
  monitor: 'n.显示器;v.监控',   monkey: 'n.猴子',   monthly: 'adj.每月的',
  monument: 'n.纪念碑',   mood: 'n.心情',   moral: 'adj.道德的',
  moreover: 'adv.此外',   morning: 'n.早上',   mortgage: 'n.抵押贷款',
  mosquito: 'n.蚊子',   moss: 'n.苔藓',   most: 'adv.最多',
  mostly: 'adv.大部分',   motel: 'n.汽车旅馆',   motion: 'n.运动',
  motivate: 'v.激励',   motive: 'n.动机',   motor: 'n.发动机',
  mount: 'v.登上',   mountain: 'n.山',   mourn: 'v.哀悼',
  mouse: 'n.老鼠;鼠标',   moustache: 'n.胡子',   mouth: 'n.嘴',
  movie: 'n.电影',   mud: 'n.泥',   mug: 'n.马克杯',
  multiple: 'adj.多样的',   multiply: 'v.乘',   murder: 'n.谋杀',
  muscle: 'n.肌肉',   museum: 'n.博物馆',   mushroom: 'n.蘑菇',
  music: 'n.音乐',   musical: 'adj.音乐的',   musician: 'n.音乐家',
  must: 'v.必须',   mutual: 'adj.相互的',   mystery: 'n.神秘',
  myth: 'n.神话',   nail: 'n.钉子;指甲',   naked: 'adj.裸体的',
  name: 'n.名字',   nap: 'n.小睡',   narrow: 'adj.狭窄的',
  nasty: 'adj.恶心的',   nation: 'n.国家',   national: 'adj.国家的',
  native: 'adj.本地的',   natural: 'adj.自然的',   naughty: 'adj.淘气的',
  naval: 'adj.海军的',   navigation: 'n.导航',   navy: 'n.海军',
  nearby: 'adj.附近的',   nearly: 'adv.将近',   neat: 'adj.整洁的',
  necessarily: 'adv.必要地',   neck: 'n.脖子',   necklace: 'n.项链',
  needle: 'n.针',   negative: 'adj.消极的',   neglect: 'v.忽视',
  negotiate: 'v.谈判',   neighbor: 'n.邻居',   neither: 'pron.两者都不',
  nerve: 'n.神经',   nervous: 'adj.紧张的',   nest: 'n.巢',
  net: 'n.网',   network: 'n.网络',   neutral: 'adj.中立的',
  nevertheless: 'adv.然而',   newly: 'adv.新近',   news: 'n.新闻',
  newspaper: 'n.报纸',   niche: 'n. niche',   niece: 'n.侄女',
  nightmare: 'n.噩梦',   nitrogen: 'n.氮',   noisy: 'adj.吵闹的',
  none: 'pron.没有一个',   nonsense: 'n.胡说',   noon: 'n.中午',
  normal: 'adj.正常的',   north: 'n.北',   northeast: 'n.东北',
  northwest: 'n.西北',   nose: 'n.鼻子',   notable: 'adj.显著的',
  note: 'n.笔记;v.注意',   notebook: 'n.笔记本',   notice: 'n.通知;v.注意到',
  notify: 'v.通知',   notion: 'n.概念',   novel: 'n.小说;adj.新颖的',
  nowadays: 'adv.如今',   nowhere: 'adv.无处',   nuclear: 'adj.核的',
  nuisance: 'n.麻烦事',   number: 'n.数字',   numerous: 'adj.众多的',
  nurse: 'n.护士',   nursery: 'n.托儿所',   nut: 'n.坚果',
  nutrition: 'n.营养',   nylon: 'n.尼龙',   obey: 'v.服从',
  object: 'n.物体;v.反对',   objective: 'n.目标;adj.客观的',   obligation: 'n.义务',
  observe: 'v.观察',   obtain: 'v.获得',   obvious: 'adj.明显的',
  occasion: 'n.场合',   occupy: 'v.占据',   occur: 'v.发生',
  ocean: 'n.海洋',   odd: 'adj.奇怪的',   offend: 'v.冒犯',
  office: 'n.办公室',   officer: 'n.官员',   official: 'adj.官方的;n.官员',
  often: 'adv.经常',   oil: 'n.油',   old: 'adj.老的',
  olive: 'n.橄榄',   onion: 'n.洋葱',   online: 'adj.在线的',
  only: 'adv.仅仅',   opera: 'n.歌剧',   operate: 'v.操作',
  opinion: 'n.观点',   opponent: 'n.对手',   opportunity: 'n.机会',
  oppose: 'v.反对',   opposite: 'adj.相反的',   optimistic: 'adj.乐观的',
  option: 'n.选项',   oral: 'adj.口头的',   orange: 'n.橙子',
  orbit: 'n.轨道',   orchestra: 'n.管弦乐队',   order: 'n.顺序;v.命令',
  ordinary: 'adj.普通的',   organ: 'n.器官',   organic: 'adj.有机的',
  organism: 'n.生物体',   organization: 'n.组织',   organize: 'v.组织',
  orient: 'v.使朝向',   origin: 'n.起源',   original: 'adj.原始的',
  ornament: 'n.装饰',   orphan: 'n.孤儿',   otherwise: 'adv.否则',
  ought: 'v.应该',   ounce: 'n.盎司',   outcome: 'n.结果',
  outdoor: 'adj.户外的',   outer: 'adj.外部的',   outing: 'n.远足',
  outlet: 'n.出口',   outline: 'n.大纲',   output: 'n.输出',
  outstanding: 'adj.杰出的',   oval: 'adj.椭圆的',   oven: 'n.烤箱',
  over: 'prep.在...上方',   overall: 'adj.总体的',   overcome: 'v.克服',
  overflow: 'v.溢出',   overhead: 'adv.在头顶上',   overlook: 'v. overlooking',
  overnight: 'adv.通宵',   overseas: 'adv.在海外',   overtake: 'v.超过',
  owe: 'v.欠',   own: 'adj.自己的',   owner: 'n.所有者',
  oxygen: 'n.氧气',   pace: 'n.速度',   pack: 'v.打包;n.包',
  package: 'n.包裹',   pad: 'n.垫子',   page: 'n.页',
  pain: 'n.疼痛',   paint: 'v.绘画;n.油漆',   painter: 'n.画家',
  pair: 'n.一对',   palace: 'n.宫殿',   pale: 'adj.苍白的',
  palm: 'n.手掌',   pan: 'n.平底锅',   panel: 'n.面板',
  panic: 'n.恐慌',   paper: 'n.纸',   parade: 'n.游行',
  paragraph: 'n.段落',   parallel: 'adj.平行的',   parcel: 'n.包裹',
  pardon: 'n.原谅',   parent: 'n.父母',   park: 'n.公园;v.停车',
  parliament: 'n.议会',   part: 'n.部分',   participate: 'v.参加',
  particle: 'n.粒子',   particular: 'adj.特别的',   partner: 'n.伙伴',
  party: 'n.聚会;政党',   passage: 'n.段落;通道',   passenger: 'n.乘客',
  passion: 'n.激情',   passive: 'adj.被动的',   passport: 'n.护照',
  password: 'n.密码',   past: 'n.过去;prep.经过',   paste: 'n.糊',
  pat: 'v.轻拍',   patch: 'n.补丁',   patent: 'n.专利',
  path: 'n.路径',   patience: 'n.耐心',   patient: 'n.病人;adj.耐心的',
  pattern: 'n.模式',   pause: 'v.暂停',   pave: 'v.铺设',
  paw: 'n.爪子',   peace: 'n.和平',   peak: 'n.顶峰',
  pear: 'n.梨',   peasant: 'n.农民',   peel: 'v.剥皮',
  peer: 'n.同龄人',   pen: 'n.笔',   penalty: 'n.惩罚',
  pencil: 'n.铅笔',   people: 'n.人们',   pepper: 'n.胡椒',
  per: 'prep.每',   perceive: 'v.感知',   percent: 'n.百分比',
  perfect: 'adj.完美的',   perform: 'v.执行',   perfume: 'n.香水',
  perhaps: 'adv.也许',   period: 'n.时期',   permanent: 'adj.永久的',
  permission: 'n.许可',   permit: 'v.允许',   person: 'n.人',
  personal: 'adj.个人的',   persuade: 'v.说服',   pet: 'n.宠物',
  petrol: 'n.汽油（英）',   phenomenon: 'n.现象',   photo: 'n.照片',
  phrase: 'n.短语',   physical: 'adj.身体的;物理的',   physics: 'n.物理',
  piano: 'n.钢琴',   pick: 'v.挑选',   picnic: 'n.野餐',
  picture: 'n.图片',   pie: 'n.馅饼',   piece: 'n.片',
  pig: 'n.猪',   pigeon: 'n.鸽子',   pile: 'n.堆',
  pill: 'n.药片',   pillar: 'n.柱子',   pillow: 'n.枕头',
  pilot: 'n.飞行员',   pin: 'n.别针',   pine: 'n.松树',
  pineapple: 'n.菠萝',   pink: 'adj.粉色的',   pioneer: 'n.先锋',
  pipe: 'n.管道',   pity: 'n.怜悯',   place: 'n.地方;v.放置',
  plain: 'adj.简单的;n.平原',   plan: 'n.计划;v.计划',   plane: 'n.飞机',
  planet: 'n.行星',   plant: 'n.植物;v.种植',   plastic: 'n.塑料;adj.塑料的',
  plate: 'n.盘子',   platform: 'n.平台',   pleasant: 'adj.愉快的',
  please: 'v.请',   pleased: 'adj.高兴的',   pleasure: 'n.快乐',
  plenty: 'n.大量',   plot: 'n.情节;v.密谋',   plug: 'n.插头',
  plunge: 'v.投入',   plural: 'adj.复数的',   plus: 'prep.加',
  pocket: 'n.口袋',   poem: 'n.诗',   poet: 'n.诗人',
  poetry: 'n.诗歌',   point: 'n.点',   poison: 'n.毒药',
  poisonous: 'adj.有毒的',   pole: 'n.极',   police: 'n.警察',
  policeman: 'n.警察',   polite: 'adj.礼貌的',   political: 'adj.政治的',
  politician: 'n.政治家',   politics: 'n.政治',   pollute: 'v.污染',
  pollution: 'n.污染',   pond: 'n.池塘',   pool: 'n.游泳池',
  poor: 'adj.贫穷的',   pop: 'n.流行音乐',   popular: 'adj.流行的',
  population: 'n.人口',   pork: 'n.猪肉',   port: 'n.港口',
  portable: 'adj.便携的',   portion: 'n.部分',   portrait: 'n.肖像',
  pose: 'v.摆姿势',   position: 'n.位置',   positive: 'adj.积极的',
  possess: 'v.拥有',   possession: 'n.财产',   possibility: 'n.可能性',
  possible: 'adj.可能的',   post: 'n.帖子;v.邮寄',   postcard: 'n.明信片',
  poster: 'n.海报',   postpone: 'v.推迟',   pot: 'n.锅',
  potato: 'n.土豆',   potential: 'adj.潜在的;n.潜力',   pound: 'n.磅;英镑',
  pour: 'v.倒',   poverty: 'n.贫困',   powder: 'n.粉末',
  power: 'n.力量',   powerful: 'adj.强大的',   practical: 'adj.实用的',
  practice: 'n.练习',   praise: 'n.赞扬',   pray: 'v.祈祷',
  precious: 'adj.珍贵的',   precise: 'adj.精确的',   predict: 'v.预测',
  preface: 'n.前言',   prefer: 'v.更喜欢',   preference: 'n.偏爱',
  pregnant: 'adj.怀孕的',   prejudice: 'n.偏见',   premier: 'n.总理',
  preparation: 'n.准备',   prepare: 'v.准备',   prescribe: 'v.开处方',
  presence: 'n.存在',   present: 'adj.现在的;n.礼物',   preserve: 'v.保存',
  president: 'n.总统',   press: 'v.按;n.新闻界',   pressure: 'n.压力',
  pretend: 'v.假装',   pretty: 'adj.漂亮的',   prevent: 'v.阻止',
  preview: 'n.预览',   previous: 'adj.先前的',   price: 'n.价格',
  pride: 'n.骄傲',   priest: 'n.牧师',   primary: 'adj.首要的',
  prime: 'adj.首要的',   primitive: 'adj.原始的',   prince: 'n.王子',
  princess: 'n.公主',   principal: 'adj.主要的;n.校长',   principle: 'n.原则',
  print: 'v.打印',   prior: 'adj.在先的',   prison: 'n.监狱',
  prisoner: 'n.囚犯',   private: 'adj.私人的',   privilege: 'n.特权',
  prize: 'n.奖品',   pro: 'n.专业人员',   probably: 'adv.可能',
  problem: 'n.问题',   procedure: 'n.程序',   proceed: 'v.继续进行',
  process: 'n.过程',   produce: 'v.生产',   product: 'n.产品',
  profession: 'n.职业',   professional: 'adj.专业的',   professor: 'n.教授',
  profile: 'n.简介',   profit: 'n.利润',   program: 'n.程序',
  progress: 'n.进步',   prohibit: 'v.禁止',   project: 'n.项目;v.投射',
  prominent: 'adj.突出的',   promise: 'n.承诺;v.承诺',   promote: 'v.促进',
  pronounce: 'v.发音',   proof: 'n.证据',   proper: 'adj.适当的',
  property: 'n.财产',   proportion: 'n.比例',   proposal: 'n.提议',
  propose: 'v.提议',   prospect: 'n.前景',   protect: 'v.保护',
  protein: 'n.蛋白质',   protest: 'v.抗议',   proud: 'adj.骄傲的',
  prove: 'v.证明',   province: 'n.省',   psychology: 'n.心理学',
  pub: 'n.酒吧',   public: 'adj.公共的',   publish: 'v.出版',
  pulse: 'n.脉搏',   pump: 'n.泵',   punch: 'v.打孔',
  punctual: 'adj.准时的',   punish: 'v.惩罚',   pupil: 'n.学生;瞳孔',
  purchase: 'v.购买',   pure: 'adj.纯的',   purple: 'adj.紫色的',
  purpose: 'n.目的',   purse: 'n.钱包',   pursue: 'v.追求',
  push: 'v.推',   puzzle: 'n.谜题',   qualification: 'n.资格',
  qualify: 'v.使合格',   quality: 'n.质量',   quantity: 'n.数量',
  quarrel: 'v.争吵',   quarter: 'n.四分之一',   queen: 'n.女王',
  question: 'n.问题',   queue: 'n.队列',   quick: 'adj.快速的',
  quiet: 'adj.安静的',   quit: 'v.退出',   quite: 'adv.相当',
  quiz: 'n.测验',   quote: 'v.引用',   rabbit: 'n.兔子',
  race: 'n.种族;比赛',   rack: 'n.架子',   radar: 'n.雷达',
  radiation: 'n.辐射',   radio: 'n.收音机',   rag: 'n.破布',
  rage: 'n.愤怒',   rail: 'n.铁轨',   railway: 'n.铁路',
  rain: 'n.雨;v.下雨',   rainbow: 'n.彩虹',   rally: 'n.集会',
  range: 'n.范围',   rank: 'n.等级',   rapid: 'adj.迅速的',
  rare: 'adj.稀有的',   rat: 'n.老鼠',   rate: 'n.比率',
  rather: 'adv.相当',   raw: 'adj.生的',   ray: 'n.光线',
  react: 'v.反应',   ready: 'adj.准备好的',   real: 'adj.真正的',
  realize: 'v.意识到',   reason: 'n.原因',   recall: 'v.回忆',
  receipt: 'n.收据',   receive: 'v.收到',   recent: 'adj.最近的',
  reception: 'n.接待',   recipe: 'n.食谱',   reckon: 'v.认为',
  recognize: 'v.认出',   recommend: 'v.推荐',   record: 'n.记录;v.记录',
  recover: 'v.恢复',   reduce: 'v.减少',   refer: 'v.参考',
  reflect: 'v.反映',   reform: 'v.改革',   refuse: 'v.拒绝',
  regard: 'v.认为',   region: 'n.地区',   register: 'v.注册',
  regret: 'v.后悔',   regular: 'adj.定期的',   regulate: 'v.调节',
  reject: 'v.拒绝',   relate: 'v.关联',   relation: 'n.关系',
  relative: 'adj.相对的;n.亲戚',   relax: 'v.放松',   release: 'v.释放',
  relevant: 'adj.相关的',   reliable: 'adj.可靠的',   relief: 'n.解脱',
  relieve: 'v.缓解',   religion: 'n.宗教',   rely: 'v.依赖',
  remain: 'v.保持',   remark: 'n.评论',   remind: 'v.提醒',
  remote: 'adj.遥远的',   remove: 'v.移除',   rent: 'v.租',
  repair: 'v.修理',   repeat: 'v.重复',   replace: 'v.替换',
  reply: 'v.回复',   report: 'n.报告;v.报告',   represent: 'v.代表',
  republic: 'n.共和国',   request: 'n.请求',   rescue: 'v.营救',
  research: 'n.研究',   resemble: 'v.像',   reserve: 'v.保留',
  resign: 'v.辞职',   resist: 'v.抵抗',   resource: 'n.资源',
  respect: 'n.尊重;v.尊重',   respond: 'v.回应',   responsible: 'adj.负责的',
  rest: 'n.休息;v.休息',   restaurant: 'n.餐厅',   restore: 'v.恢复',
  restrict: 'v.限制',   result: 'n.结果',   retain: 'v.保持',
  retire: 'v.退休',   reveal: 'v.揭示',   revenue: 'n.收入',
  reverse: 'v.反转',   review: 'n.复习;v.复习',   revise: 'v.修订',
  revolution: 'n.革命',   reward: 'n.奖励',   rhythm: 'n.节奏',
  rice: 'n.米饭',   rich: 'adj.富有的',   rid: 'v.摆脱',
  ride: 'v.骑',   rifle: 'n.步枪',   right: 'adj.正确的;n.右边',
  rigid: 'adj.严格的',   ring: 'n.戒指;v.响铃',   ripe: 'adj.成熟的',
  rise: 'v.上升',   risk: 'n.风险;v.冒险',   rival: 'n.对手',
  river: 'n.河',   road: 'n.路',   roar: 'v.咆哮',
  roast: 'v.烤',   rob: 'v.抢劫',   robot: 'n.机器人',
  rock: 'n.岩石;v.摇晃',   role: 'n.角色',   roll: 'v.滚动',
  romantic: 'adj.浪漫的',   roof: 'n.屋顶',   room: 'n.房间',
  root: 'n.根',   rope: 'n.绳子',   rose: 'n.玫瑰',
  rough: 'adj.粗糙的',   round: 'adj.圆的;prep.围绕',   route: 'n.路线',
  routine: 'n.常规',   row: 'n.排;v.划船',   royal: 'adj.皇家的',
  rub: 'v.擦',   rubber: 'n.橡胶',   rubbish: 'n.垃圾',
  rude: 'adj.粗鲁的',   rug: 'n.小地毯',   ruin: 'v.毁坏',
  rule: 'n.规则;v.统治',   rumor: 'n.谣言',   rural: 'adj.乡村的',
  rush: 'v.冲',   rust: 'n.锈',   sack: 'n.袋子',
  sacrifice: 'n.牺牲',   sad: 'adj.悲伤的',   safe: 'adj.安全的',
  safety: 'n.安全',   sail: 'v.航行',   sailor: 'n.水手',
  salad: 'n.沙拉',   salary: 'n.薪水',   sale: 'n.销售',
  salt: 'n.盐',   same: 'adj.相同的',   sample: 'n.样品',
  sand: 'n.沙子',   sandwich: 'n.三明治',   satellite: 'n.卫星',
  satisfaction: 'n.满意',   satisfy: 'v.满足',   sauce: 'n.酱汁',
  save: 'v.保存;拯救',   scale: 'n.规模;刻度',   scan: 'v.扫描',
  scar: 'n.伤疤',   scare: 'v.惊吓',   scarf: 'n.围巾',
  scene: 'n.场景',   schedule: 'n.时间表',   scheme: 'n.方案',
  scholar: 'n.学者',   scholarship: 'n.奖学金',   school: 'n.学校',
  science: 'n.科学',   scientific: 'adj.科学的',   scissors: 'n.剪刀',
  scold: 'v.责骂',   scope: 'n.范围',   score: 'n.分数;v.得分',
  scream: 'v.尖叫',   screen: 'n.屏幕',   screw: 'n.螺丝',
  script: 'n.脚本',   sea: 'n.海',   seal: 'n.海豹;封印',
  search: 'v.搜索',   season: 'n.季节',   seat: 'n.座位',
  second: 'num.第二',   secret: 'n.秘密;adj.秘密的',   secretary: 'n.秘书',
  section: 'n.部分',   sector: 'n.部门',   secure: 'adj.安全的;v.保护',
  security: 'n.安全',   seed: 'n.种子',   seek: 'v.寻找',
  seize: 'v.抓住',   select: 'v.选择',   self: 'n.自我',
  senior: 'adj.高级的',   sense: 'n.感觉',   sensitive: 'adj.敏感的',
  sentence: 'n.句子',   separate: 'v.分开;adj.分开的',   series: 'n.系列',
  serious: 'adj.严肃的',   servant: 'n.仆人',   session: 'n.会议',
  settle: 'v.定居',   settlement: 'n.定居点',   several: 'adj.几个',
  severe: 'adj.严重的',   sew: 'v.缝纫',   sex: 'n.性别',
  shade: 'n.阴影',   shadow: 'n.影子',   shake: 'v.摇晃',
  shall: 'v.将要',   shallow: 'adj.浅的',   shame: 'n.羞耻',
  shape: 'n.形状;v.塑造',   share: 'v.分享;n.份额',   shark: 'n.鲨鱼',
  sharp: 'adj.锋利的',   shave: 'v.刮胡子',   she: 'pron.她',
  shed: 'v.脱落;n.棚',   sheep: 'n.绵羊',   sheet: 'n.床单',
  shelf: 'n.架子',   shell: 'n.壳',   shelter: 'n.避难所',
  shield: 'n.盾牌;v.保护',   shift: 'v.转移',   shine: 'v.发光',
  ship: 'n.船',   shirt: 'n.衬衫',   shiver: 'v.颤抖',
  shock: 'n.震惊;v.使震惊',   shoe: 'n.鞋',   shoot: 'v.射击',
  shop: 'n.商店',   shore: 'n.海岸',   short: 'adj.短的',
  shortage: 'n.短缺',   shot: 'n.射击',   should: 'v.应该',
  shoulder: 'n.肩膀',   shout: 'v.喊叫',   shower: 'n.淋浴',
  shut: 'v.关闭',   shy: 'adj.害羞的',   sick: 'adj.生病的',
  side: 'n.边',   sidewalk: 'n.人行道',   sigh: 'v.叹气',
  sight: 'n.视力;景象',   sign: 'n.标志;v.签名',   signal: 'n.信号',
  signature: 'n.签名',   significant: 'adj.重要的',   silence: 'n.沉默',
  silent: 'adj.沉默的',   silk: 'n.丝绸',   silly: 'adj.愚蠢的',
  silver: 'n.银',   similar: 'adj.相似的',   simple: 'adj.简单的',
  simply: 'adv.简单地',   sin: 'n.罪',   since: 'prep.自从;conj.因为',
  sing: 'v.唱歌',   sink: 'v.下沉',   sir: 'n.先生',
  sister: 'n.姐妹',   site: 'n.地点',   situation: 'n.情况',
  size: 'n.尺寸',   skate: 'v.滑冰',   sketch: 'n.素描',
  ski: 'v.滑雪',   skill: 'n.技能',   skin: 'n.皮肤',
  skip: 'v.跳过',   skirt: 'n.裙子',   skull: 'n.头骨',
  sky: 'n.天空',   slam: 'v.砰地关上',   slave: 'n.奴隶',
  sleeve: 'n.袖子',   slice: 'n.片',   slide: 'v.滑动',
  slight: 'adj.轻微的',   slim: 'adj.苗条的',   slip: 'v.滑倒',
  slope: 'n.斜坡',   slow: 'adj.慢的',   small: 'adj.小的',
  smart: 'adj.聪明的',   smash: 'v.粉碎',   smell: 'n.气味;v.闻',
  smile: 'v.微笑',   smoke: 'n.烟;v.吸烟',   smooth: 'adj.光滑的',
  snake: 'n.蛇',   snap: 'v.折断',   snow: 'n.雪;v.下雪',
  soak: 'v.浸泡',   soap: 'n.肥皂',   soccer: 'n.足球',
  social: 'adj.社会的',   society: 'n.社会',   sock: 'n.袜子',
  soda: 'n.苏打',   sofa: 'n.沙发',   soft: 'adj.软的',
  software: 'n.软件',   soil: 'n.土壤',   soldier: 'n.士兵',
  sole: 'adj.唯一的',   solid: 'adj.固体的;n.固体',   solution: 'n.解决方案',
  solve: 'v.解决',   some: 'pron.一些',   somebody: 'pron.某人',
  somehow: 'adv.以某种方式',   someone: 'pron.某人',   something: 'pron.某事',
  sometimes: 'adv.有时',   somewhat: 'adv.有点',   somewhere: 'adv.某处',
  son: 'n.儿子',   song: 'n.歌',   soon: 'adv.很快',
  sore: 'adj.酸痛的',   sorrow: 'n.悲伤',   sort: 'n.种类;v.分类',
  soul: 'n.灵魂',   sound: 'n.声音;adj.健康的',   soup: 'n.汤',
  source: 'n.来源',   south: 'n.南',   southeast: 'n.东南',
  southwest: 'n.西南',   space: 'n.空间',   spare: 'adj.多余的',
  spark: 'n.火花',   speaker: 'n.演讲者',   special: 'adj.特别的',
  species: 'n.物种',   specific: 'adj.具体的',   speech: 'n.演讲',
  speed: 'n.速度',   spell: 'v.拼写',   sphere: 'n.球体',
  spider: 'n.蜘蛛',   spill: 'v.溢出',   spin: 'v.旋转',
  spirit: 'n.精神',   spit: 'v.吐',   splash: 'v.溅',
  split: 'v.分裂',   spoil: 'v.破坏',   spokesman: 'n.发言人',
  sponge: 'n.海绵',   sponsor: 'n.赞助商',   spoon: 'n.勺子',
  sport: 'n.运动',   spot: 'n.地点;v.发现',   spouse: 'n.配偶',
  spray: 'n.喷雾',   spread: 'v.传播',   spring: 'n.春天;泉水',
  spy: 'n.间谍',   square: 'n.正方形',   squeeze: 'v.挤压',
  squirrel: 'n.松鼠',   stable: 'adj.稳定的',   stadium: 'n.体育场',
  staff: 'n.员工',   stage: 'n.舞台',   stain: 'n.污渍',
  stair: 'n.楼梯',   stake: 'n.赌注',   stale: 'adj.不新鲜的',
  stamp: 'n.邮票',   standard: 'n.标准',   star: 'n.星星',
  stare: 'v.凝视',   starve: 'v.挨饿',   state: 'n.州;状态',
  statement: 'n.声明',   station: 'n.车站',   statue: 'n.雕像',
  status: 'n.地位',   steady: 'adj.稳定的',   steak: 'n.牛排',
  steal: 'v.偷',   steam: 'n.蒸汽',   steel: 'n.钢',
  steep: 'adj.陡峭的',   steer: 'v.驾驶',   stem: 'n.茎',
  step: 'n.步骤;v.踩',   stereotype: 'n.刻板印象',   stick: 'v.粘贴;n.棍',
  sticky: 'adj.粘的',   stiff: 'adj.硬的',   still: 'adv.仍然',
  stimulate: 'v.刺激',   sting: 'v.蜇',   stir: 'v.搅拌',
  stock: 'n.股票',   stomach: 'n.胃',   stone: 'n.石头',
  stool: 'n.凳子',   store: 'n.商店;v.储存',   storm: 'n.暴风雨',
  story: 'n.故事',   stove: 'n.炉子',   straight: 'adj.直的',
  strain: 'n.紧张',   strange: 'adj.奇怪的',   stranger: 'n.陌生人',
  strategy: 'n.策略',   straw: 'n.稻草',   strawberry: 'n.草莓',
  stream: 'n.小溪',   street: 'n.街道',   strength: 'n.力量',
  strengthen: 'v.加强',   stress: 'n.压力;v.强调',   stretch: 'v.伸展',
  strict: 'adj.严格的',   strike: 'v.打击',   string: 'n.线',
  strip: 'n.条;v.剥去',   stripe: 'n.条纹',   stroke: 'n.中风;v.抚摸',
  strong: 'adj.强壮的',   structure: 'n.结构',   struggle: 'v.奋斗',
  student: 'n.学生',   studio: 'n.工作室',   study: 'n.学习;v.学习',
  stuff: 'n.东西',   stupid: 'adj.愚蠢的',   style: 'n.风格',
  subject: 'n.科目;主语',   submarine: 'n.潜艇',   submit: 'v.提交',
  subscribe: 'v.订阅',   substance: 'n.物质',   suburb: 'n.郊区',
  subway: 'n.地铁',   succeed: 'v.成功',   success: 'n.成功',
  successful: 'adj.成功的',   such: 'adj.这样的',   suck: 'v.吸',
  sudden: 'adj.突然的',   suffer: 'v.遭受',   sugar: 'n.糖',
  suicide: 'n.自杀',   suit: 'n.西装;v.适合',   suitable: 'adj.合适的',
  suitcase: 'n.手提箱',   sum: 'n.总和',   summarize: 'v.总结',
  summer: 'n.夏天',   summit: 'n.顶峰',   sun: 'n.太阳',
  sunlight: 'n.阳光',   sunny: 'adj.晴朗的',   sunrise: 'n.日出',
  sunset: 'n.日落',   sunshine: 'n.阳光',   super: 'adj.超级的',
  superb: 'adj.极好的',   superior: 'adj.优越的',   supermarket: 'n.超市',
  supper: 'n.晚餐',   supply: 'n.供应;v.供应',   support: 'n.支持;v.支持',
  suppose: 'v.假设',   supreme: 'adj.最高的',   sure: 'adj.确定的',
  surface: 'n.表面',   surgeon: 'n.外科医生',   surgery: 'n.手术',
  surplus: 'n.过剩',   surprise: 'n.惊喜;v.使惊讶',   surrender: 'v.投降',
  surround: 'v.包围',   survey: 'n.调查;v.调查',   survive: 'v.幸存',
  suspect: 'v.怀疑;n.嫌疑人',   suspend: 'v.暂停',   sustain: 'v.维持',
  swallow: 'v.吞;n.燕子',   swamp: 'n.沼泽',   swan: 'n.天鹅',
  swear: 'v.发誓',   sweat: 'n.汗',   sweater: 'n.毛衣',
  sweep: 'v.扫',   sweet: 'adj.甜的',   swell: 'v.膨胀',
  swift: 'adj.迅速的',   swim: 'v.游泳',   swing: 'v.摇摆',
  switch: 'n.开关;v.切换',   sword: 'n.剑',   symbol: 'n.象征',
  sympathy: 'n.同情',   symptom: 'n.症状',   system: 'n.系统',
  table: 'n.桌子',   tablet: 'n.平板电脑',   tackle: 'v.处理',
  tag: 'n.标签',   tail: 'n.尾巴',   tailor: 'n.裁缝',
  tale: 'n.故事',   talent: 'n.才能',   talk: 'v.谈话',
  tall: 'adj.高的',   tank: 'n.坦克;水箱',   tap: 'v.轻敲;n.水龙头',
  tape: 'n.磁带',   target: 'n.目标',   task: 'n.任务',
  taste: 'n.味道;v.品尝',   tax: 'n.税',   taxi: 'n.出租车',
  tea: 'n.茶',   teach: 'v.教',   teacher: 'n.老师',
  team: 'n.团队',   tear: 'n.眼泪;v.撕裂',   tease: 'v.取笑',
  technical: 'adj.技术的',   technique: 'n.技巧',   technology: 'n.技术',
  teenager: 'n.青少年',   telephone: 'n.电话',   telescope: 'n.望远镜',
  television: 'n.电视',   temper: 'n.脾气',   temperature: 'n.温度',
  temple: 'n.寺庙',   temporary: 'adj.暂时的',   tempt: 'v.诱惑',
  ten: 'num.十',   tenant: 'n.租户',   tend: 'v.倾向于',
  tendency: 'n.趋势',   tennis: 'n.网球',   tense: 'adj.紧张的;n.时态',
  tension: 'n.紧张',   tent: 'n.帐篷',   term: 'n.术语;学期',
  terminal: 'n.终端;adj.末期的',   terrible: 'adj.糟糕的',   terrific: 'adj.极好的',
  territory: 'n.领土',   terror: 'n.恐怖',   test: 'n.测试;v.测试',
  text: 'n.文本',   textbook: 'n.课本',   texture: 'n.质地',
  than: 'conj.比',   thank: 'v.感谢',   that: 'pron.那个',
  the: 'art.这/那',   theater: 'n.剧院',   theft: 'n.偷窃',
  theme: 'n.主题',   then: 'adv.然后',   theory: 'n.理论',
  therapy: 'n.治疗',   there: 'adv.那里',   thereby: 'adv.因此',
  therefore: 'adv.因此',   thermometer: 'n.温度计',   these: 'pron.这些',
  thesis: 'n.论文',   thick: 'adj.厚的',   thief: 'n.小偷',
  thin: 'adj.瘦的;薄的',   thing: 'n.事情',   thirsty: 'adj.渴的',
  thirteen: 'num.十三',   thirty: 'num.三十',   this: 'pron.这个',
  thorn: 'n.刺',   thorough: 'adj.彻底的',   those: 'pron.那些',
  though: 'conj.虽然',   thousand: 'num.千',   thread: 'n.线',
  threat: 'n.威胁',   threaten: 'v.威胁',   three: 'num.三',
  throat: 'n.喉咙',   throne: 'n.王位',   through: 'prep.通过',
  throughout: 'prep.遍及',   throw: 'v.扔',   thumb: 'n.拇指',
  thunder: 'n.雷',   thus: 'adv.因此',   tick: 'v.打勾',
  ticket: 'n.票',   tide: 'n.潮汐',   tidy: 'adj.整洁的',
  tie: 'n.领带;v.系',   tiger: 'n.老虎',   tight: 'adj.紧的',
  tile: 'n.瓦片',   till: 'prep.直到',   timber: 'n.木材',
  time: 'n.时间',   tin: 'n.锡;罐头',   tiny: 'adj.微小的',
  tip: 'n.小费;尖端',   tire: 'v.使疲劳;n.轮胎',   tired: 'adj.累的',
  tissue: 'n.纸巾',   title: 'n.标题',   to: 'prep.到',
  toast: 'n.吐司;祝酒',   tobacco: 'n.烟草',   today: 'adv.今天',
  toe: 'n.脚趾',   together: 'adv.一起',   toilet: 'n.厕所',
  tolerate: 'v.容忍',   tomato: 'n.西红柿',   tomb: 'n.坟墓',
  tomorrow: 'adv.明天',   tone: 'n.音调',   tongue: 'n.舌头',
  tonight: 'adv.今晚',   tool: 'n.工具',   tooth: 'n.牙齿',
  topic: 'n.话题',   torch: 'n.手电筒',   tornado: 'n.龙卷风',
  torture: 'n.折磨',   toss: 'v.扔',   total: 'adj.总的',
  touch: 'v.触摸;n.触觉',   tough: 'adj.坚韧的',   tour: 'n.旅游',
  tourist: 'n.游客',   toward: 'prep.朝向',   towel: 'n.毛巾',
  tower: 'n.塔',   town: 'n.城镇',   toxic: 'adj.有毒的',
  toy: 'n.玩具',   trace: 'n.痕迹;v.追踪',   track: 'n.轨道;v.追踪',
  tractor: 'n.拖拉机',   trade: 'n.贸易;v.交易',   tradition: 'n.传统',
  traffic: 'n.交通',   tragedy: 'n.悲剧',   trail: 'n.小径',
  train: 'n.火车;v.训练',   training: 'n.训练',   trait: 'n.特征',
  trap: 'n.陷阱;v.困住',   trash: 'n.垃圾',   travel: 'v.旅行',
  tray: 'n.托盘',   treasure: 'n.宝藏',   treat: 'v.对待;n.款待',
  treaty: 'n.条约',   tree: 'n.树',   tremble: 'v.颤抖',
  trend: 'n.趋势',   trial: 'n.审判',   triangle: 'n.三角形',
  tribe: 'n.部落',   trick: 'n.诡计',   trip: 'n.旅行;v.绊倒',
  troop: 'n.军队',   trophy: 'n.奖杯',   trouble: 'n.麻烦',
  trousers: 'n.裤子',   truck: 'n.卡车',   true: 'adj.真实的',
  trumpet: 'n.小号',   trunk: 'n.树干;行李箱',   trust: 'n.信任;v.信任',
  truth: 'n.真理',   tube: 'n.管子',   tuition: 'n.学费',
  tune: 'n.曲调',   tunnel: 'n.隧道',   turkey: 'n.火鸡;土耳其',
  tutor: 'n.家教',   twelve: 'num.十二',   twenty: 'num.二十',
  twice: 'adv.两次',   twin: 'n.双胞胎',   twist: 'v.扭曲',
  type: 'n.类型;v.打字',   typical: 'adj.典型的',   tyre: 'n.轮胎（英）',
  ugly: 'adj.丑陋的',   umbrella: 'n.雨伞',   uncle: 'n.叔叔',
  under: 'prep.在...之下',   undergo: 'v.经历',   underground: 'adj.地下的',
  underline: 'v.强调',   undertake: 'v.承担',   uniform: 'n.制服',
  union: 'n.工会',   unique: 'adj.独特的',   unit: 'n.单位',
  unite: 'v.联合',   universe: 'n.宇宙',   university: 'n.大学',
  unless: 'conj.除非',   until: 'prep.直到',   unusual: 'adj.不寻常的',
  up: 'adv.向上',   update: 'v.更新',   upgrade: 'v.升级',
  upon: 'prep.在...之上',   upper: 'adj.上面的',   upset: 'adj.心烦的;v.使心烦',
  upstairs: 'adv.楼上',   urge: 'v.催促',   urgent: 'adj.紧急的',
  useful: 'adj.有用的',   useless: 'adj.无用的',   user: 'n.用户',
  usual: 'adj.通常的',   usually: 'adv.通常',   vacation: 'n.假期',
  vacuum: 'n.真空',   vague: 'adj.模糊的',   vain: 'adj.徒劳的',
  valley: 'n.山谷',   valuable: 'adj.有价值的',   value: 'n.价值',
  van: 'n.货车',   vanish: 'v.消失',   vapor: 'n.蒸汽',
  variable: 'adj.可变的',   variation: 'n.变化',   variety: 'n.多样性',
  various: 'adj.各种各样的',   vase: 'n.花瓶',   vast: 'adj.巨大的',
  vegetable: 'n.蔬菜',   vehicle: 'n.车辆',   venture: 'n.冒险',
  verb: 'n.动词',   verse: 'n.诗节',   version: 'n.版本',
  vertical: 'adj.垂直的',   very: 'adv.非常',   vessel: 'n.船只',
  veteran: 'n.老兵',   veto: 'v.否决',   via: 'prep.通过',
  vice: 'n.恶习',   victim: 'n.受害者',   victory: 'n.胜利',
  video: 'n.视频',   view: 'n.观点;v.看',   village: 'n.村庄',
  vinegar: 'n.醋',   violate: 'v.违反',   violence: 'n.暴力',
  violent: 'adj.暴力的',   violin: 'n.小提琴',   virtual: 'adj.虚拟的',
  virtue: 'n.美德',   virus: 'n.病毒',   visible: 'adj.可见的',
  vision: 'n.视力;愿景',   visit: 'v.参观',   visitor: 'n.访客',
  visual: 'adj.视觉的',   vital: 'adj.至关重要的',   vitamin: 'n.维生素',
  vivid: 'adj.生动的',   vocabulary: 'n.词汇',   voice: 'n.嗓音',
  volcano: 'n.火山',   volleyball: 'n.排球',   volume: 'n.体积;音量',
  volunteer: 'n.志愿者',   vote: 'v.投票',   voyage: 'n.航行',
  wage: 'n.工资',   waist: 'n.腰',   waiter: 'n.服务员',
  wake: 'v.醒来',   wall: 'n.墙',   wallet: 'n.钱包',
  wander: 'v.漫游',   war: 'n.战争',   ward: 'n.病房',
  warehouse: 'n.仓库',   warm: 'adj.温暖的',   warn: 'v.警告',
  warning: 'n.警告',   wash: 'v.洗',   waste: 'n.浪费;v.浪费',
  water: 'n.水',   waterfall: 'n.瀑布',   wave: 'n.波浪;v.挥手',
  wax: 'n.蜡',   way: 'n.方式',   weak: 'adj.虚弱的',
  wealth: 'n.财富',   weapon: 'n.武器',   wear: 'v.穿',
  weather: 'n.天气',   weave: 'v.编织',   web: 'n.网',
  website: 'n.网站',   wedding: 'n.婚礼',   weed: 'n.杂草',
  week: 'n.周',   weekday: 'n.工作日',   weekly: 'adj.每周的',
  weekend: 'n.周末',   weigh: 'v.称重',   weight: 'n.重量',
  weird: 'adj.奇怪的',   welcome: 'v.欢迎',   welfare: 'n.福利',
  well: 'adv.好',   west: 'n.西',   western: 'adj.西方的',
  wet: 'adj.湿的',   whale: 'n.鲸鱼',   what: 'pron.什么',
  whatever: 'pron.无论什么',   wheat: 'n.小麦',   wheel: 'n.轮子',
  when: 'adv.当...时',   whenever: 'conj.每当',   where: 'adv.哪里',
  wherever: 'conj.无论哪里',   whether: 'conj.是否',   which: 'pron.哪个',
  while: 'conj.当...时',   whip: 'v.鞭打',   whisper: 'v.低语',
  whistle: 'n.口哨',   white: 'adj.白色的',   who: 'pron.谁',
  whoever: 'pron.无论谁',   whole: 'adj.整个的',   whom: 'pron.谁',
  whose: 'pron.谁的',   why: 'adv.为什么',   wide: 'adj.宽的',
  widespread: 'adj.广泛的',   widow: 'n.寡妇',   width: 'n.宽度',
  wife: 'n.妻子',   wild: 'adj.野生的',   will: 'v.将;n.意志',
  willing: 'adj.愿意的',   wind: 'n.风;v.缠绕',   window: 'n.窗户',
  windy: 'adj.有风的',   wine: 'n.酒',   wing: 'n.翅膀',
  winter: 'n.冬天',   wipe: 'v.擦',   wire: 'n.电线',
  wisdom: 'n.智慧',   wise: 'adj.聪明的',   wish: 'v.希望',
  wit: 'n.才智',   with: 'prep.和',   withdraw: 'v.撤回',
  within: 'prep.在...之内',   without: 'prep.没有',   witness: 'n.证人;v.见证',
  wolf: 'n.狼',   woman: 'n.女人',   wonder: 'n.惊奇;v.想知道',
  wonderful: 'adj.精彩的',   wood: 'n.木头',   wooden: 'adj.木制的',
  wool: 'n.羊毛',   word: 'n.单词',   world: 'n.世界',
  worm: 'n.虫子',   worry: 'v.担心',   worse: 'adj.更差的',
  worship: 'v.崇拜',   worst: 'adj.最差的',   worth: 'adj.值得的',
  worthwhile: 'adj.值得的',   worthy: 'adj.值得的',   would: 'v.将会',
  wound: 'n.伤口;v.伤害',   wrap: 'v.包裹',   wreck: 'n.残骸',
  wrestle: 'v.摔跤',   wrinkle: 'n.皱纹',   wrist: 'n.手腕',
  wrong: 'adj.错误的',   yard: 'n.院子',   year: 'n.年',
  yell: 'v.大喊',   yellow: 'adj.黄色的',   yes: 'adv.是',
  yesterday: 'adv.昨天',   yet: 'adv.还',   yield: 'v.屈服;产生',
  yoga: 'n.瑜伽',   young: 'adj.年轻的',   youth: 'n.青年',
  zebra: 'n.斑马',   zero: 'num.零',   zone: 'n.区域',
  zoo: 'n.动物园',
  hello: 'int.你好',   hi: 'int.嗨',   hey: 'int.嘿',
  thanks: 'n.感谢',   sorry: 'adj.抱歉的',   bye: 'int.再见',
  ok: 'adj.好的',   okay: 'adj.好的',   no: 'adv.不;adj.没有的',
  congratulations: 'n.祝贺',   apple: 'n.苹果',   banana: 'n.香蕉',
  watermelon: 'n.西瓜',   peach: 'n.桃子',   cherry: 'n.樱桃',
  mango: 'n.芒果',   computer: 'n.电脑',   phone: 'n.电话;手机',
  chair: 'n.椅子',   bed: 'n.床',   bag: 'n.包',
  backpack: 'n.背包',   bottle: 'n.瓶子',   bowl: 'n.碗',
  chopsticks: 'n.筷子',   napkin: 'n.餐巾',   toothbrush: 'n.牙刷',
  toothpaste: 'n.牙膏',   shampoo: 'n.洗发水',   comb: 'n.梳子',
  camera: 'n.相机',   fridge: 'n.冰箱',   refrigerator: 'n.冰箱',
  washer: 'n.洗衣机',   dryer: 'n.烘干机',   air: 'n.空气',
  conditioner: 'n.空调',   light: 'n.光;adj.轻的',   bulb: 'n.灯泡',
  candle: 'n.蜡烛',   man: 'n.男人',   boy: 'n.男孩',
  girl: 'n.女孩',   child: 'n.孩子',   baby: 'n.婴儿',
  family: 'n.家庭',   mother: 'n.母亲',   mom: 'n.妈妈',
  mum: 'n.妈妈（英）',   father: 'n.父亲',   dad: 'n.爸爸',
  brother: 'n.兄弟',   grandfather: 'n.祖父',   grandmother: 'n.祖母',
  grandpa: 'n.爷爷',   grandma: 'n.奶奶',   aunt: 'n.阿姨',
  nephew: 'n.侄子',   home: 'n.家;adv.在家',   house: 'n.房子',
  bedroom: 'n.卧室',   bathroom: 'n.浴室',   car: 'n.汽车',
  bus: 'n.公交车',   bike: 'n.自行车',   bicycle: 'n.自行车',
  cab: 'n.出租车',   metro: 'n.地铁',   tram: 'n.有轨电车',
  boat: 'n.小船',   ferry: 'n.渡轮',   airplane: 'n.飞机',
  aircraft: 'n.飞行器',   rocket: 'n.火箭',   spaceship: 'n.宇宙飞船',
  motorcycle: 'n.摩托车',   ambulance: 'n.救护车',   city: 'n.城市',
  country: 'n.国家;乡村',   capital: 'n.首都',   earth: 'n.地球;土地',
  campus: 'n.校园',   cinema: 'n.电影院',   gymnasium: 'n.体育馆',
  aquarium: 'n.水族馆',   amusement: 'n.娱乐',   beach: 'n.海滩',
  cave: 'n.洞穴',   bridge: 'n.桥',   castle: 'n.城堡',
  bakery: 'n.面包店',   butcher: 'n.肉店',   pharmacy: 'n.药房',
  bookstore: 'n.书店',   stationery: 'n.文具',   hairdresser: 'n.理发店',
  bank: 'n.银行',   cafe: 'n.咖啡馆',   bar: 'n.酒吧',
  mosque: 'n.清真寺',   airport: 'n.机场',   food: 'n.食物',
  breakfast: 'n.早餐',   snack: 'n.零食',   bread: 'n.面包',
  bun: 'n.小圆面包',   cookie: 'n.饼干',   biscuit: 'n.饼干（英）',
  pizza: 'n.披萨',   hotdog: 'n.热狗',   noodle: 'n.面条',
  pasta: 'n.意大利面',   porridge: 'n.粥',   dumpling: 'n.饺子',
  steamed: 'adj.蒸的',   beef: 'n.牛肉',   sausage: 'n.香肠',
  bacon: 'n.培根',   shrimp: 'n.虾',   crab: 'n.螃蟹',
  lobster: 'n.龙虾',   yogurt: 'n.酸奶',   candy: 'n.糖果',
  honey: 'n.蜂蜜',   popcorn: 'n.爆米花',   chip: 'n.薯片;芯片',
  fries: 'n.薯条',   pudding: 'n.布丁',   beverage: 'n.饮料',
  coke: 'n.可乐',   beer: 'n.啤酒',   alcohol: 'n.酒精',
  meatball: 'n.肉丸',   tofu: 'n.豆腐',   carrot: 'n.胡萝卜',
  cabbage: 'n.卷心菜',   cucumber: 'n.黄瓜',   pea: 'n.豌豆',
  bean: 'n.豆子',   lettuce: 'n.生菜',   spinach: 'n.菠菜',
  radish: 'n.萝卜',   eggplant: 'n.茄子',   celery: 'n.芹菜',
  broccoli: 'n.西兰花',   cauliflower: 'n.花菜',   red: 'adj.红色的;n.红色',
  blue: 'adj.蓝色的;n.蓝色',   green: 'adj.绿色的;n.绿色',   black: 'adj.黑色的;n.黑色',
  brown: 'adj.棕色的;n.棕色',   grey: 'adj.灰色的;n.灰色（英）',   golden: 'adj.金色的',
  cat: 'n.猫',   bird: 'n.鸟',   goose: 'n.鹅',
  cock: 'n.公鸡',   rooster: 'n.公鸡',   hare: 'n.野兔',
  bear: 'n.熊',   deer: 'n.鹿',   lizard: 'n.蜥蜴',
  crocodile: 'n.鳄鱼',   turtle: 'n.乌龟',   toad: 'n.蟾蜍',
  bee: 'n.蜜蜂',   ant: 'n.蚂蚁',   butterfly: 'n.蝴蝶',
  dragonfly: 'n.蜻蜓',   scorpion: 'n.蝎子',   snail: 'n.蜗牛',
  penguin: 'n.企鹅',   dolphin: 'n.海豚',   camel: 'n.骆驼',
  kangaroo: 'n.袋鼠',   panda: 'n.熊猫',   koala: 'n.考拉',
  hippo: 'n.河马',   rhino: 'n.犀牛',   bat: 'n.蝙蝠',
  owl: 'n.猫头鹰',   crow: 'n.乌鸦',   parrot: 'n.鹦鹉',
  peacock: 'n.孔雀',   crane: 'n.鹤',   seagull: 'n.海鸥',
  dove: 'n.鸽子',   sparrow: 'n.麻雀',   sunflower: 'n.向日葵',
  lily: 'n.百合',   lotus: 'n.荷花',   moon: 'n.月亮',
  woods: 'n.树林',   big: 'adj.大的',   high: 'adj.高的',
  deep: 'adj.深的',   heavy: 'adj.重的',   fast: 'adj.快的',
  new: 'adj.新的',   ancient: 'adj.古老的',   dirty: 'adj.脏的',
  messy: 'adj.凌乱的',   clear: 'adj.清楚的',   bright: 'adj.明亮的',
  shiny: 'adj.发亮的',   good: 'adj.好的',   nice: 'adj.好的',
  fine: 'adj.好的',   amazing: 'adj.惊人的',   awesome: 'adj.令人惊叹的',
  marvelous: 'adj.了不起的',   bad: 'adj.坏的',   awful: 'adj.可怕的',
  horrible: 'adj.可怕的',   beautiful: 'adj.美丽的',   cute: 'adj.可爱的',
  handsome: 'adj.英俊的',   gorgeous: 'adj.华丽的',   attractive: 'adj.有吸引力的',
  charming: 'adj.迷人的',   hot: 'adj.热的',   cold: 'adj.冷的',
  damp: 'adj.潮湿的',   rainy: 'adj.下雨的',   cloudy: 'adj.多云的',
  snowy: 'adj.下雪的',   stormy: 'adj.暴风雨的',   foggy: 'adj.有雾的',
  frosty: 'adj.霜冻的',   happy: 'adj.快乐的',   cheerful: 'adj.愉快的',
  merry: 'adj.欢乐的',   joyful: 'adj.喜悦的',   delighted: 'adj.高兴的',
  satisfied: 'adj.满意的',   excited: 'adj.兴奋的',   thrilled: 'adj.非常兴奋的',
  unhappy: 'adj.不开心的',   depressed: 'adj.沮丧的',   miserable: 'adj.痛苦的',
  gloomy: 'adj.忧郁的',   angry: 'adj.生气的',   annoyed: 'adj.恼怒的',
  irritated: 'adj.恼怒的',   frustrated: 'adj.沮丧的',   afraid: 'adj.害怕的',
  scared: 'adj.恐惧的',   frightened: 'adj.受惊的',   terrified: 'adj.极度恐惧的',
  fearful: 'adj.担心的',   anxious: 'adj.焦虑的',   worried: 'adj.担心的',
  embarrassed: 'adj.尴尬的',   ashamed: 'adj.羞愧的',   bored: 'adj.无聊的',
  exhausted: 'adj.筋疲力尽的',   sleepy: 'adj.困倦的',   hungry: 'adj.饥饿的',
  ill: 'adj.生病的',   healthy: 'adj.健康的',   comfortable: 'adj.舒适的',
  uncomfortable: 'adj.不舒服的',   relaxed: 'adj.放松的',   peaceful: 'adj.平静的',
  impatient: 'adj.不耐烦的',   careful: 'adj.小心的',   cautious: 'adj.谨慎的',
  careless: 'adj.粗心的',   kind: 'adj.善良的;n.种类',   selfish: 'adj.自私的',
  honest: 'adj.诚实的',   dishonest: 'adj.不诚实的',   faithful: 'adj.忠实的',
  brave: 'adj.勇敢的',   courageous: 'adj.勇敢的',   cowardly: 'adj.胆小的',
  clever: 'adj.聪明的',   talented: 'adj.有才华的',   creative: 'adj.有创造力的',
  hardworking: 'adj.勤奋的',   diligent: 'adj.勤奋的',   active: 'adj.活跃的',
  energetic: 'adj.精力充沛的',   lively: 'adj.活泼的',   enthusiastic: 'adj.热情的',
  passionate: 'adj.热情的',   arrogant: 'adj.傲慢的',   confident: 'adj.自信的',
  pessimistic: 'adj.悲观的',   realistic: 'adj.现实的',   sentimental: 'adj.多愁善感的',
  emotional: 'adj.情绪化的',   humorous: 'adj.幽默的',   interested: 'adj.感兴趣的',
  boring: 'adj.无聊的',   interesting: 'adj.有趣的',   amusing: 'adj.有趣的',
  peculiar: 'adj. peculiar',   surprising: 'adj.令人惊讶的',   shocking: 'adj.令人震惊的',
  astonishing: 'adj.令人惊讶的',   exciting: 'adj.令人兴奋的',   frightening: 'adj.可怕的',
  terrifying: 'adj.可怕的',   disgusting: 'adj.令人恶心的',   unpleasant: 'adj.不愉快的',
  inconvenient: 'adj.不方便的',   appropriate: 'adj.适当的',   accurate: 'adj.准确的',
  partial: 'adj.部分的',   crowded: 'adj.拥挤的',   spacious: 'adj.宽敞的',
  enough: 'adj.足够的',   adequate: 'adj.足够的',   abundant: 'adj.丰富的',
  wealthy: 'adj.富裕的',   cheap: 'adj.便宜的',   worthless: 'adj.无价值的',
  effective: 'adj.有效的',   mighty: 'adj.强大的',   fragile: 'adj.脆弱的',
  tender: 'adj.温柔的;嫩的',   hard: 'adj.困难的;硬的',   blunt: 'adj.钝的',
  pointed: 'adj.尖的',   rectangular: 'adj.长方形的',   triangular: 'adj.三角形的',
  circular: 'adj.圆形的',   curved: 'adj.弯曲的',   crooked: 'adj.弯曲的',
  bent: 'adj.弯曲的',   dangerous: 'adj.危险的',   harmful: 'adj.有害的',
  harmless: 'adj.无害的',   deadly: 'adj.致命的',   radioactive: 'adj.放射性的',
  flammable: 'adj.易燃的',   shaky: 'adj.摇晃的',   wobbly: 'adj.摇摆的',
  loose: 'adj.松的',   flexible: 'adj.灵活的',   elastic: 'adj.有弹性的',
  metallic: 'adj.金属的',   woolen: 'adj.羊毛的',   really: 'adv.真的',
  too: 'adv.也;太',   so: 'conj.所以;adv.如此',   extremely: 'adv.极其',
  incredibly: 'adv.难以置信地',   terribly: 'adv.非常',   awfully: 'adv.非常',
  fairly: 'adv.相当',   relatively: 'adv.相对地',   slightly: 'adv.轻微地',
  barely: 'adv.勉强',   scarcely: 'adv.几乎不',   rarely: 'adv.很少',
  seldom: 'adv.很少',   never: 'adv.从不',   always: 'adv.总是',
  normally: 'adv.通常',   generally: 'adv.通常',   typically: 'adv.典型地',
  commonly: 'adv.通常',   frequently: 'adv.频繁地',   regularly: 'adv.定期地',
  repeatedly: 'adv.反复地',   constantly: 'adv.不断地',   continuously: 'adv.连续地',
  occasionally: 'adv.偶尔',   now: 'adv.现在',   currently: 'adv.当前',
  presently: 'adv.目前',   recently: 'adv.最近',   shortly: 'adv.不久',
  immediately: 'adv.立即',   instantly: 'adv.立刻',   promptly: 'adv.迅速地',
  quickly: 'adv.快速地',   rapidly: 'adv.迅速地',   swiftly: 'adv.迅速地',
  slowly: 'adv.慢慢地',   gradually: 'adv.逐渐地',   finally: 'adv.最后',
  ultimately: 'adv.最终',   lastly: 'adv.最后',   before: 'prep.在...之前',
  after: 'prep.在...之后',   afterwards: 'adv.后来',   later: 'adv.后来',
  earlier: 'adv.早些时候',   ago: 'adv.以前',   beforehand: 'adv.预先',
  already: 'adv.已经',   once: 'conj.一旦',   again: 'adv.再次',
  just: 'adv.刚刚;仅仅',   merely: 'adv.仅仅',   purely: 'adv.纯粹地',
  exactly: 'adv.确切地',   precisely: 'adv.精确地',   absolutely: 'adv.绝对地',
  totally: 'adv.完全地',   completely: 'adv.完全地',   entirely: 'adv.完全地',
  fully: 'adv.充分地',   thoroughly: 'adv.彻底地',   partly: 'adv.部分地',
  almost: 'adv.几乎',   approximately: 'adv.大约',   about: 'prep.关于',
  around: 'prep.围绕',   roughly: 'adv.大约',   more: 'adv.更多',
  less: 'adv.更少',   least: 'adv.最少',   much: 'adv.很',
  also: 'adv.也',   as: 'conj.因为;当...时',   either: 'adv.也（否定）',
  besides: 'adv.此外',   furthermore: 'adv.此外',   however: 'adv.然而',
  nonetheless: 'adv.尽管如此',   although: 'conj.虽然',   despite: 'prep.尽管',
  regardless: 'adv.不管',   whichever: 'pron.无论哪个',   everywhere: 'adv.到处',
  anywhere: 'adv.任何地方',   down: 'adv.向下',   ahead: 'adv.在前面',
  behind: 'prep.在...后面',   above: 'prep.在...之上',   below: 'prep.在...之下',
  outside: 'adv.在外面',   indoors: 'adv.在室内',   outdoors: 'adv.在室外',
  downstairs: 'adv.楼下',   homeward: 'adv.向家',   abroad: 'adv.在国外',
  alone: 'adv.独自',   apart: 'adv.分开',   aside: 'adv.在旁边',
  away: 'adv.离开',   off: 'prep.离开',   out: 'adv.出去',
  one: 'num.一',   two: 'num.二',   four: 'num.四',
  five: 'num.五',   six: 'num.六',   seven: 'num.七',
  eight: 'num.八',   nine: 'num.九',   eleven: 'num.十一',
  fourteen: 'num.十四',   fifteen: 'num.十五',   sixteen: 'num.十六',
  seventeen: 'num.十七',   eighteen: 'num.十八',   nineteen: 'num.十九',
  forty: 'num.四十',   fifty: 'num.五十',   sixty: 'num.六十',
  seventy: 'num.七十',   eighty: 'num.八十',   ninety: 'num.九十',
  hundred: 'num.百',   billion: 'num.十亿',   countless: 'adj.无数的',
  first: 'num.第一',   third: 'num.第三',   fourth: 'num.第四',
  fifth: 'num.第五',   sixth: 'num.第六',   seventh: 'num.第七',
  eighth: 'num.第八',   ninth: 'num.第九',   tenth: 'num.第十',
  next: 'adj.下一个的',   every: 'adj.每个',   each: 'pron.每个',
  all: 'pron.所有',   both: 'pron.两者都',   triple: 'adj.三倍的',
  single: 'adj.单一的',   monday: 'n.星期一',   tuesday: 'n.星期二',
  wednesday: 'n.星期三',   thursday: 'n.星期四',   friday: 'n.星期五',
  saturday: 'n.星期六',   sunday: 'n.星期天',   january: 'n.一月',
  february: 'n.二月',   april: 'n.四月',   june: 'n.六月',
  july: 'n.七月',   august: 'n.八月',   september: 'n.九月',
  october: 'n.十月',   november: 'n.十一月',   december: 'n.十二月',
  autumn: 'n.秋天',   top: 'n.顶部',   bottom: 'n.底部',
  center: 'n.中心',   between: 'prep.在...之间',   among: 'prep.在...之中',
  beside: 'prep.在旁边',   near: 'prep.靠近',   i: 'pron.我',
  you: 'pron.你',   he: 'pron.他',   it: 'pron.它',
  we: 'pron.我们',   they: 'pron.他们',   me: 'pron.我（宾格）',
  him: 'pron.他（宾格）',   her: 'pron.她（宾格）',   us: 'pron.我们（宾格）',
  them: 'pron.他们（宾格）',   my: 'pron.我的',   your: 'pron.你的',
  his: 'pron.他的',   its: 'pron.它的',   our: 'pron.我们的',
  their: 'pron.他们的',   yours: 'pron.你的',   hers: 'pron.她的',
  ours: 'pron.我们的',   theirs: 'pron.他们的',   myself: 'pron.我自己',
  yourself: 'pron.你自己',   himself: 'pron.他自己',   herself: 'pron.她自己',
  itself: 'pron.它自己',   ourselves: 'pron.我们自己',   yourselves: 'pron.你们自己',
  themselves: 'pron.他们自己',   how: 'adv.如何',   and: 'conj.和',
  but: 'conj.但是',   or: 'conj.或者',   because: 'conj.因为',
  at: 'prep.在',   in: 'prep.在...里',   on: 'prep.在...上',
  for: 'prep.为了',   of: 'prep.的',   across: 'prep.穿过',
  by: 'prep.通过;在...旁边',   beyond: 'prep.超过',   along: 'prep.沿着',
  against: 'prep.反对',   towards: 'prep.朝向',   not: 'adv.不',
  can: 'v.能',

  action: 'n.行动',
  activity: 'n.活动',
  actor: 'n.演员',
  actress: 'n.女演员',
  actual: 'adj.实际的',
  actually: 'adv.实际上',
  adult: 'n.成年人',
  advantage: 'n.优势',
  adventure: 'n.冒险',
  advertisement: 'n.广告',
  advice: 'n.建议',
  affair: 'n.事情',
  agency: 'n.代理',
  agent: 'n.代理人',
  aggressive: 'adj.侵略性的',
  agreement: 'n.协议',
  airline: 'n.航空公司',
  alive: 'adj.活着的',
  aloud: 'adv.大声地',
  altogether: 'adv.总共',
  amaze: 'v.使惊奇',
  anger: 'n.愤怒',
  animal: 'n.动物',
  another: 'adj.另一个',
  anxiety: 'n.焦虑',
  anybody: 'pron.任何人',
  anyone: 'pron.任何人',
  anything: 'pron.任何事',
  anyway: 'adv.无论如何',
  apparent: 'adj.明显的',
  apparently: 'adv.显然',
  appendix: 'n.附录',
  appetite: 'n.食欲',
  applaud: 'v.鼓掌',
  applicant: 'n.申请人',
  application: 'n.申请',
  appointment: 'n.约会',
  architect: 'n.建筑师',
  area: 'n.地区',
  army: 'n.军队',
  arrangement: 'n.安排',
  arrival: 'n.到达',
  arrow: 'n.箭',
  art: 'n.艺术',
  article: 'n.文章',
  artist: 'n.艺术家',
  asleep: 'adj.睡着的',
  aspect: 'n.方面',
  assistance: 'n.帮助',
  assistant: 'n.助手',
  associate: 'v.联系',
  association: 'n.协会',
  assure: 'v.保证',
  astonish: 'v.使惊讶',
  athlete: 'n.运动员',
  atmosphere: 'n.大气',
  attempt: 'v.尝试',
  attention: 'n.注意',
  attitude: 'n.态度',
  audience: 'n.观众',
  author: 'n.作者',
  authority: 'n.权威',
  automatic: 'adj.自动的',
  available: 'adj.可用的',
  average: 'adj.平均的',
  award: 'n.奖',
  aware: 'adj.意识到的',
  awkward: 'adj.尴尬的',
  background: 'n.背景',
  backward: 'adv.向后',
  bacteria: 'n.细菌',
  badly: 'adv.非常',
  balance: 'n.平衡',
  ball: 'n.球',
  band: 'n.乐队',
  bark: 'v.吠叫',
  barn: 'n.谷仓',
  barrel: 'n.桶',
  base: 'n.基础',
  baseball: 'n.棒球',
  basement: 'n.地下室',
  basic: 'adj.基本的',
  basin: 'n.盆地',
  basis: 'n.基础',
  basket: 'n.篮子',
  basketball: 'n.篮球',
  bath: 'n.洗澡',
  bathtub: 'n.浴缸',
  battery: 'n.电池',
  battle: 'n.战斗',
  bay: 'n.海湾',
  beard: 'n.胡须',
  beast: 'n.野兽',
  beauty: 'n.美',
  beg: 'v.乞求',
  behalf: 'n.代表',
  behavior: 'n.行为',
  belief: 'n.信念',
  bell: 'n.铃',
  belt: 'n.腰带',
  bench: 'n.长凳',
  bend: 'v.弯曲',
  beneath: 'prep.在...下方',
  berry: 'n.浆果',
  best: 'adj.最好的',
  better: 'adj.更好的',
  bill: 'n.账单',
  biography: 'n.传记',
  biology: 'n.生物',
  birth: 'n.出生',
  birthday: 'n.生日',
  bit: 'n.一点',
  bitter: 'adj.苦的',
  blackboard: 'n.黑板',
  blade: 'n.刀片',
  blank: 'adj.空白的',
  blanket: 'n.毯子',
  blind: 'adj.盲的',
  block: 'n.街区',
  blood: 'n.血',
  bloom: 'v.开花',
  blossom: 'n.花朵',
  board: 'n.木板',
  boast: 'v.吹嘘',
  body: 'n.身体',
  bold: 'adj.大胆的',
  bone: 'n.骨头',
  bonus: 'n.奖金',
  boom: 'n.繁荣',
  boot: 'n.靴子',
  border: 'n.边界',
  bore: 'v.使厌烦',
  boss: 'n.老板',
  bound: 'adj.注定的',
  boundary: 'n.边界',
  box: 'n.盒子',
  brain: 'n.大脑',
  brick: 'n.砖',
  bride: 'n.新娘',
  brief: 'adj.简短的',
  brilliant: 'adj.杰出的',
  broad: 'adj.宽的',
  bubble: 'n.气泡',
  bucket: 'n.桶',
  budget: 'n.预算',
  buffet: 'n.自助餐',
  bug: 'n.虫子',
  bunch: 'n.一束',
  bundle: 'n.捆',
  burst: 'v.爆发',
  business: 'n.商业',
  busy: 'adj.忙的',
  cabin: 'n.小屋',
  cabinet: 'n.橱柜',
  cable: 'n.电缆',
  cafeteria: 'n.自助餐厅',
  cage: 'n.笼子',
  calendar: 'n.日历',
  campaign: 'n.运动',
  cancer: 'n.癌症',
  candidate: 'n.候选人',
  canteen: 'n.食堂',
  cap: 'n.帽子',
  capable: 'adj.有能力的',
  capacity: 'n.容量',
  captain: 'n.船长',
  carbon: 'n.碳',
  card: 'n.卡片',
  career: 'n.职业',
  carpet: 'n.地毯',
  cartoon: 'n.卡通',
  case: 'n.情况',
  cassette: 'n.磁带',
  casual: 'adj.随意的',
  catalog: 'n.目录',
  category: 'n.类别',
  cater: 'v.提供餐饮',
  cathedral: 'n.大教堂',
  cattle: 'n.牛',
  caution: 'n.小心',
  ceiling: 'n.天花板',
  celebrity: 'n.名人',
  cell: 'n.细胞',
  cent: 'n.分',
  central: 'adj.中心的',
  century: 'n.世纪',
  ceremony: 'n.仪式',
  certain: 'adj.确定的',
  certainly: 'adv.当然',
  certificate: 'n.证书',
  chairman: 'n.主席',
  chance: 'n.机会',
  chaos: 'n.混乱',
  character: 'n.性格',
  charity: 'n.慈善',
  chart: 'n.图表',
  check: 'v.检查',
  cheek: 'n.脸颊',
  chef: 'n.厨师',
  chemical: 'adj.化学的',
  chemist: 'n.化学家',
  chemistry: 'n.化学',
  cheque: 'n.支票',
  chess: 'n.国际象棋',
  chew: 'v.咀嚼',
  childhood: 'n.童年',
  chimney: 'n.烟囱',
  chin: 'n.下巴',
  choir: 'n.合唱团',
  choke: 'v.窒息',
  chop: 'v.砍',
  chorus: 'n.合唱',
  christian: 'adj.基督教的',
  christmas: 'n.圣诞节',
  circuit: 'n.电路',
  circulate: 'v.循环',
  circumstance: 'n.环境',
  circus: 'n.马戏团',
  cite: 'v.引用',
  civil: 'adj.公民的',
  civilian: 'n.平民',
  civilization: 'n.文明',
  class: 'n.班级',
  classic: 'adj.经典的',
  classical: 'adj.古典的',
  classmate: 'n.同学',
  classroom: 'n.教室',
  clause: 'n.条款',
  client: 'n.客户',
  climate: 'n.气候',
  closet: 'n.壁橱',
  clothes: 'n.衣服',
  clothing: 'n.服装',
  collaborate: 'v.合作',
  colleague: 'n.同事',
  collection: 'n.收藏',
  collision: 'n.碰撞',
  color: 'n.颜色',
  comedy: 'n.喜剧',
  comic: 'adj.喜剧的',
  commerce: 'n.商业',
  commercial: 'adj.商业的',
  commitment: 'n.承诺',
  committee: 'n.委员会',
  common: 'adj.常见的',
  communication: 'n.交流',
  communism: 'n.共产主义',
  communist: 'n.共产党员',
  companion: 'n.同伴',
  company: 'n.公司',
  compass: 'n.指南针',
  compensate: 'v.补偿',
  competence: 'n.能力',
  competition: 'n.竞争',
  component: 'n.组件',
  composition: 'n.作文',
  comprehension: 'n.理解',
  comprehensive: 'adj.综合的',
  comprise: 'v.包含',
  compromise: 'n.妥协',
  compulsory: 'adj.强制的',
  concept: 'n.概念',
  concert: 'n.音乐会',
  conclusion: 'n.结论',
  conference: 'n.会议',
  consensus: 'n.共识',
  consequence: 'n.结果',
  conservative: 'adj.保守的',
  considerate: 'adj.体贴的',
  consistent: 'adj.一致的',
  constitution: 'n.宪法',
  construction: 'n.建设',
  consultant: 'n.顾问',
  container: 'n.容器',
  continent: 'n.大陆',
  controversial: 'adj.有争议的',
  convenience: 'n.方便',
  conventional: 'adj.传统的',
  cooker: 'n.炊具',
  corner: 'n.角落',
  courtyard: 'n.庭院',
  crayon: 'n.蜡笔',
  criminal: 'n.罪犯',
  criterion: 'n.标准',
  critical: 'adj.批评的',
  criticism: 'n.批评',
  crossing: 'n.十字路口',
  crossroads: 'n.交叉路口',
  cube: 'n.立方体',
  cuisine: 'n.烹饪',
  currency: 'n.货币',
  curriculum: 'n.课程',
  cyclist: 'n.骑自行车的人',
  dairy: 'n.乳制品',
  dam: 'n.水坝',
  danger: 'n.危险',
  dash: 'v.猛冲',
  database: 'n.数据库',
  day: 'n.天',
  deadline: 'n.截止日期',
  deaf: 'adj.聋的',
  dear: 'adj.亲爱的',
  deed: 'n.行为',
  defense: 'n.防御',
  deficiency: 'n.缺乏',
  definite: 'adj.明确的',
  delete: 'v.删除',
  deliberately: 'adv.故意地',
  delicate: 'adj.精致的',
  delicious: 'adj.美味的',
  delight: 'n.高兴',
  department: 'n.部门',
  departure: 'n.出发',
  depth: 'n.深度',
  deputy: 'n.副手',
  description: 'n.描述',
  desire: 'n.欲望',
  desperate: 'adj.绝望的',
  dessert: 'n.甜点',
  destination: 'n.目的地',
  detective: 'n.侦探',
  dial: 'v.拨号',
  dialog: 'n.对话',
  dictation: 'n.听写',
  differ: 'v.不同',
  difference: 'n.差异',
  different: 'adj.不同的',
  difficult: 'adj.困难的',
  difficulty: 'n.困难',
  digest: 'v.消化',
  dilemma: 'n.困境',
  dine: 'v.进餐',
  dinosaur: 'n.恐龙',
  dioxide: 'n.二氧化物',
  direction: 'n.方向',
  director: 'n.导演',
  directory: 'n.目录',
  disability: 'n.残疾',
  disabled: 'adj.残疾的',
  discard: 'v.丢弃',
  discharge: 'v.释放',
  discovery: 'n.发现',
  discriminate: 'v.歧视',
  discussion: 'n.讨论',
  distinction: 'n.区别',
  diverse: 'adj.多样的',
  division: 'n.部门',
  dizzy: 'adj.头晕的',
  dormitory: 'n.宿舍',
  downtown: 'n.市中心',
  drawback: 'n.缺点',
  drought: 'n.干旱',
  drown: 'v.淹死',
  due: 'adj.到期的',
  dusk: 'n.黄昏',
  dustbin: 'n.垃圾箱',
  dusty: 'adj.布满灰尘的',
  dynamic: 'adj.动态的',
  dynasty: 'n.王朝',
  early: 'adj.早的',
  easily: 'adv.容易地',
  eastern: 'adj.东方的',
  easy: 'adj.容易的',
  ecology: 'n.生态学',
  edition: 'n.版本',
  editor: 'n.编辑',
  education: 'n.教育',
  educator: 'n.教育家',
  election: 'n.选举',
  electrical: 'adj.电的',
  electricity: 'n.电',
  electronic: 'adj.电子的',
  elementary: 'adj.初级的',
  elevator: 'n.电梯',
  elsewhere: 'adv.别处',
  email: 'n.电子邮件',
  embassy: 'n.大使馆',
  emergency: 'n.紧急情况',
  emigrate: 'v.移民',
  engineer: 'n.工程师',
  enjoyable: 'adj.愉快的',
  enlarge: 'v.扩大',
  enquire: 'v.询问',
  enterprise: 'n.企业',
  entertainment: 'n.娱乐',
  equality: 'n.平等',
  equipment: 'n.设备',
  eraser: 'n.橡皮',
  error: 'n.错误',
  erupt: 'v.爆发',
  essential: 'adj.必要的',
  euro: 'n.欧元',
  evening: 'n.晚上',
  everybody: 'pron.每个人',
  everyone: 'pron.每个人',
  everything: 'pron.一切',
  evident: 'adj.明显的',
  evolution: 'n.进化',
  exhibition: 'n.展览',
  existence: 'n.存在',
  experience: 'n.经验',
  explanation: 'n.解释',
  explicit: 'adj.明确的',
  expression: 'n.表达',
  extension: 'n.延伸',
  extensive: 'adj.广泛的',
  extra: 'adj.额外的',
  extraordinary: 'adj.非凡的',
  eyesight: 'n.视力',
  facial: 'adj.面部的',
  failure: 'n.失败',
  famous: 'adj.著名的',
  fantasy: 'n.幻想',
  fare: 'n.车费',
  farmer: 'n.农民',
  fax: 'n.传真',
  feast: 'n.盛宴',
  fellow: 'n.家伙',
  fiber: 'n.纤维',
  fingernail: 'n.指甲',
  fireworks: 'n.烟花',
  fisherman: 'n.渔夫',
  fond: 'adj.喜欢的',
  foreigner: 'n.外国人',
  fortnight: 'n.两周',
  fortunate: 'adj.幸运的',
  franc: 'n.法郎',
  freeway: 'n.高速公路',
  friendship: 'n.友谊',
  frontier: 'n.边疆',
  furnished: 'adj.有家具的',
  game: 'n.游戏',
  garment: 'n.衣服',
  gay: 'adj.快乐的',
  general: 'adj.一般的',
  geography: 'n.地理',
  globe: 'n.地球',
  government: 'n.政府',
  gram: 'n.克',
  grammar: 'n.语法',
  grandchild: 'n.孙子',
  granddaughter: 'n.孙女',
  grandparent: 'n.祖父母',
  grandson: 'n.孙子',
  granny: 'n.奶奶',
  guidance: 'n.指导',
  gymnastics: 'n.体操',
  haircut: 'n.理发',
  handicap: 'n.障碍',
  handkerchief: 'n.手帕',
  handwriting: 'n.书法',
  happiness: 'n.幸福',
  headmaster: 'n.校长',
  health: 'n.健康',
  heart: 'n.心脏',
  historian: 'n.历史学家',
  history: 'n.历史',
  homeland: 'n.祖国',
  hometown: 'n.家乡',
  homework: 'n.作业',
  hopeful: 'adj.有希望的',
  hopeless: 'adj.无望的',
  hostess: 'n.女主人',
  housework: 'n.家务',
  humour: 'n.幽默',
  hunter: 'n.猎人',
  hurricane: 'n.飓风',
  identification: 'n.识别',
  identity: 'n.身份',
  illegal: 'adj.非法的',
  illness: 'n.疾病',
  immigration: 'n.移民',
  importance: 'n.重要性',
  important: 'adj.重要的',
  impossible: 'adj.不可能的',
  impression: 'n.印象',
  independent: 'adj.独立的',
  industrial: 'adj.工业的',
  information: 'n.信息',
  injury: 'n.伤害',
  institution: 'n.机构',
  instruction: 'n.指示',
  insure: 'v.投保',
  intelligence: 'n.智力',
  intention: 'n.意图',
  internet: 'n.互联网',
  interpreter: 'n.译员',
  introduction: 'n.介绍',
  invention: 'n.发明',
  invitation: 'n.邀请',
  jeep: 'n.吉普车',
  jewelry: 'n.珠宝',
  journalist: 'n.记者',
  judgement: 'n.判断',
  junk: 'n.垃圾',
  key: 'n.钥匙',
  kilogram: 'n.千克',
  kilometer: 'n.千米',
  kindness: 'n.善良',
  lab: 'n.实验室',
  lame: 'adj.瘸的',
  lantern: 'n.灯笼',
  liberate: 'v.解放',
  librarian: 'n.图书管理员',
  like: 'v.喜欢',
  litre: 'n.升',
  litter: 'n.垃圾',
  location: 'n.位置',
  lucky: 'adj.幸运的',
  madam: 'n.女士',
  mail: 'n.邮件',
  mainland: 'n.大陆',
  manage: 'v.管理',
  manager: 'n.经理',
  mankind: 'n.人类',
  maple: 'n.枫树',
  mask: 'n.面具',
  mass: 'n.大量',
  mathematics: 'n.数学',
  media: 'n.媒体',
  medieval: 'adj.中世纪的',
  mend: 'v.修理',
  metre: 'n.米',
  ministry: 'n.部',
  minute: 'n.分钟',
  misunderstand: 'v.误解',
  month: 'n.月',
  motivation: 'n.动机',
  mustard: 'n.芥末',
  nationality: 'n.国籍',
  nature: 'n.自然',
  necessary: 'adj.必要的',
  night: 'n.夜晚',
  noble: 'adj.高贵的',
  nobody: 'pron.没人',
  nod: 'v.点头',
  noise: 'n.噪音',
  nor: 'conj.也不',
  northern: 'adj.北方的',
  nothing: 'pron.没什么',
  numb: 'adj.麻木的',
  observation: 'n.观察',
  occupation: 'n.职业',
  olympic: 'adj.奥林匹克的',
  onto: 'prep.到...上',
  operation: 'n.手术',
  operator: 'n.操作员',
  optional: 'adj.可选的',
  outward: 'adv.向外',
  overweight: 'adj.超重的',
  ownership: 'n.所有权',
  ox: 'n.牛',
  pacific: 'adj.和平的',
  packet: 'n.小包',
  painful: 'adj.痛苦的',
  painting: 'n.绘画',
  pancake: 'n.薄饼',
  parking: 'n.停车',
  passerby: 'n.路人',
  pavement: 'n.人行道',
  pedestrian: 'n.行人',
  penny: 'n.便士',
  percentage: 'n.百分比',
  performance: 'n.表现',
  performer: 'n.表演者',
  personnel: 'n.人员',
  pest: 'n.害虫',
  photograph: 'n.照片',
  photographer: 'n.摄影师',
  physician: 'n.医生',
  physicist: 'n.物理学家',
  pint: 'n.品脱',
  player: 'n.玩家',
  playground: 'n.操场',
  policy: 'n.政策',
  polish: 'v.擦亮',
  porter: 'n.搬运工',
  postage: 'n.邮费',
  postman: 'n.邮递员',
  practise: 'v.练习',
  prescription: 'n.处方',
  production: 'n.生产',
  pronunciation: 'n.发音',
  properly: 'adv.适当地',
  protection: 'n.保护',
  protective: 'adj.保护的',
  quake: 'n.地震',
  quota: 'n.配额',
  quotation: 'n.引用',
  racial: 'adj.种族的',
  raincoat: 'n.雨衣',
  rainfall: 'n.降雨',
  random: 'adj.随机的',
  reaction: 'n.反应',
  reasonable: 'adj.合理的',
  rebuild: 'v.重建',
  receiver: 'n.接收器',
  recite: 'v.背诵',
  recorder: 'n.录音机',
  recreation: 'n.娱乐',
  recycle: 'v.回收',
  reference: 'n.参考',
  refresh: 'v.刷新',
  regulation: 'n.规定',
  relationship: 'n.关系',
  relay: 'n.接力',
  religious: 'adj.宗教的',
  reporter: 'n.记者',
  representative: 'n.代表',
  reputation: 'n.声誉',
  resistance: 'n.抵抗',
  resolution: 'n.决议',
  resolve: 'v.解决',
  resort: 'n.度假胜地',
  responsibility: 'n.责任',
  restriction: 'n.限制',
  rhyme: 'n.韵',
  riddle: 'n.谜语',
  ridiculous: 'adj.荒谬的',
  rot: 'v.腐烂',
  rugby: 'n.橄榄球',
  ruler: 'n.尺子',
  russia: 'n.俄罗斯',
  russian: 'adj.俄罗斯的',
  rusty: 'adj.生锈的',
  sacred: 'adj.神圣的',
  sailing: 'n.帆船运动',
  salesman: 'n.推销员',
  saleswoman: 'n.女推销员',
  salty: 'adj.咸的',
  salute: 'v.敬礼',
  scenery: 'n.风景',
  schoolbag: 'n.书包',
  schoolboy: 'n.男学生',
  schoolgirl: 'n.女学生',
  scientist: 'n.科学家',
  scratch: 'v.抓',
  sculpture: 'n.雕塑',
  seaside: 'n.海边',
  semester: 'n.学期',
  separation: 'n.分离',
  settler: 'n.定居者',
  shabby: 'adj.破旧的',
  shopkeeper: 'n.店主',
  shortcoming: 'n.缺点',
  shorts: 'n.短裤',
  shrink: 'v.收缩',
  sickness: 'n.疾病',
  sightseeing: 'n.观光',
  significance: 'n.意义',
  simplify: 'v.简化',
  sincerely: 'adv.真诚地',
  singer: 'n.歌手',
  skilled: 'adj.熟练的',
  skillful: 'adj.熟练的',
  slavery: 'n.奴隶制',
  slogan: 'n.口号',
  sneaker: 'n.运动鞋',
  sneeze: 'v.打喷嚏',
  sniff: 'v.嗅',
  sob: 'v.啜泣',
  socialism: 'n.社会主义',
  socialist: 'n.社会主义者',
  socket: 'n.插座',
  solar: 'adj.太阳的',
  sour: 'adj.酸的',
  southern: 'adj.南方的',
  souvenir: 'n.纪念品',
  sow: 'v.播种',
  spade: 'n.铲子',
  specialist: 'n.专家',
  spelling: 'n.拼写',
  splendid: 'adj.壮丽的',
  spokeswoman: 'n.女发言人',
  starvation: 'n.饥饿',
  statistic: 'n.统计',
  steward: 'n.乘务员',
  stewardess: 'n.空姐',
  stocking: 'n.长袜',
  stomachache: 'n.胃痛',
  storage: 'n.储存',
  strait: 'n.海峡',
  stubborn: 'adj.固执的',
  subjective: 'adj.主观的',
  substitute: 'n.替代品',
  suite: 'n.套房',
  summary: 'n.摘要',
  sunburn: 'n.晒伤',
};
// ==========================================
// 本地词典查询 — 零延迟
// ==========================================
function lookupDictionary(text: string): string | null {
  const lower = text.trim().toLowerCase();
  return DICTIONARY[lower] || null;
}

// ==========================================
// Hook — 纯本地翻译，零网络依赖
// ==========================================
export function useTranslator() {
  const [isTranslating, setIsTranslating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const translate = useCallback(async (text: string): Promise<string> => {
    const trimmed = text.trim();
    if (!trimmed) return '';

    setIsTranslating(true);
    setError(null);

    // 本地词典 — 零延迟，带词性标注
    const dictResult = lookupDictionary(trimmed);
    if (dictResult) {
      setIsTranslating(false);
      return dictResult;
    }

    setError('未收录该词，请手动输入翻译');
    setIsTranslating(false);
    return '';
  }, []);

  return { translate, isTranslating, error };
}
